#!/usr/bin/env python3
"""seed-hebrew-egyptian.py — Hebrew A1.1, A1.2, A2 and Egyptian A1.1, A1.2, A2"""

import psycopg2, json

DB_URL = "postgresql://neondb_owner:npg_wRBXT6Azv0Vj@ep-late-sea-aqyed9xw-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

def v(term, meaning, notes=None):
    d = {"term": term, "meaning": meaning}
    if notes: d["notes"] = notes
    return d
def L(tf, cs, kv, lo):
    return {"textFragment": tf, "contentSummary": cs, "keyVocabulary": kv, "learningObjectives": lo}

# ── EBRAICO BIBLICO A1.1 — 12 lezioni ─────────────────────────────────────────
EB_A11 = [
  L("בְּרֵאשִׁית בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם וְאֵת הָאָרֶץ (Genesi 1,1)",
    "Lezione 1: introduzione all'ebraico biblico. Si presenta l'alfabeto ebraico (alef-bet) come sistema consonantico con vocalizzazione masoretica (niqqud). La frase di Genesi 1,1 è il testo fondamentale di partenza: si legge da destra a sinistra, si identifica il verbo (bara'), il soggetto (Elohim) e il complemento oggetto (et ha-shamayim ve-et ha-aretz).",
    [v("בְּרֵאשִׁית","in principio (bet + reshit)"), v("בָּרָא","creò (qal perf. 3ª masch. sing.)"), v("אֱלֹהִים","Dio (pl. maestatis)"), v("אֵת","particella dell'oggetto diretto"), v("הַשָּׁמַיִם","i cieli (ha- = articolo)"), v("וְ","e (vav copulativo)"), v("הָאָרֶץ","la terra")],
    "Lo studente impara a leggere l'alfabeto ebraico nelle sue lettere fondamentali. Riconosce la struttura destra-sinistra della scrittura. Identifica articolo, congiunzione e particella dell'oggetto in Genesi 1,1. Comprende il concetto di vocalizzazione masoretica."),
  L("וְהָאָרֶץ הָיְתָה תֹהוּ וָבֹהוּ וְחֹשֶׁךְ עַל-פְּנֵי תְהֹום (Genesi 1,2)",
    "Lezione 2: il verbo essere (hayah) al perfetto femminile. Si lavora sulla struttura del verbo ebraico: radice trilitterale (ה-י-ה), pattern del qal perfetto. Si introduce il concetto di tohu va-vohu come espressione idiomatica (caos primordiale). Il lessico della creazione.",
    [v("הָיְתָה","era (qal perf. femm. sing. di ה-י-ה)"), v("תֹהוּ וָבֹהוּ","caos, vuoto informe (coppia allitterante)"), v("חֹשֶׁךְ","oscurità, buio"), v("עַל-פְּנֵי","sulla superficie di (prep. composta)"), v("תְהֹום","abisso, oceano primordiale")],
    "Lo studente riconosce il verbo hayah (essere) al perfetto. Comprende la struttura della radice trilitterale. Legge Genesi 1,2 nella vocalizzazione masoretica. Conosce il concetto di tohu va-vohu come termine cosmologico."),
  L("וַיֹּאמֶר אֱלֹהִים יְהִי אֹור וַיְהִי-אֹור (Genesi 1,3)",
    "Lezione 3: l'imperfetto (yiqtol) e il vav-consecutive. L'ebraico biblico usa vav + imperfetto (wayyiqtol) per narrare eventi passati in sequenza. Si analizza wa-yomer (disse) e yehi (sia!) come iussivo. Il discorso diretto nella narrativa biblica.",
    [v("וַיֹּאמֶר","e disse (wayyiqtol qal di א-מ-ר)"), v("יְהִי","sia! (iussivo qal di ה-י-ה)"), v("אֹור","luce"), v("וַיְהִי","e fu (wayyiqtol di ה-י-ה)"), v("wayyiqtol","vav-consecutive + imperfetto = narrativo passato")],
    "Lo studente comprende il sistema wayyiqtol come forma narrativa del passato. Distingue iussivo (yehi) da imperfetto (yihyeh). Legge la formula della creazione (yehi... wayyehi). Riconosce il discorso diretto nella narrativa biblica."),
  L("שְׁמַע יִשְׂרָאֵל יְהוָה אֱלֹהֵינוּ יְהוָה אֶחָד (Deuteronomio 6,4)",
    "Lezione 4: lo Shema' Israel come testo fondamentale. Si lavora sui suffissi possessivi (-nu = nostro). Si introduce il nome divino YHWH (tetragramma). L'aggettivo numerale echad (uno) come predicato nominale. Struttura della frase nominale pura in ebraico (senza copula).",
    [v("שְׁמַע","ascolta! (imperativo qal di ש-מ-ע)"), v("יִשְׂרָאֵל","Israele"), v("יְהוָה","YHWH (tetragramma, nome divino)"), v("אֱלֹהֵינוּ","il nostro Dio (-nu = suffisso 1ª pl.)"), v("אֶחָד","uno (aggettivo numerale)")],
    "Lo studente comprende la struttura della frase nominale pura (senza copula). Usa i suffissi possessivi (-nu). Legge e comprende lo Shema' Israel. Conosce il valore liturgico del testo nella tradizione ebraica."),
  L("בְּרֵאשִׁית בָּרָא אֱלֹהִים — Il verbo ebraico: radici e binyanim. La radice ב-ר-א (bara') nel qal. Primo schema: qal perfetto maschile singolare: qāṭal (3ms), qāṭalt (2ms), qāṭaltī (1cs).",
    "Lezione 5: il sistema verbale ebraico. Si presenta il paradigma del qal perfetto con la radice model קָטַל (qatal = uccidere). Si mostrano le desinenze del perfetto: 3ms (qāṭal), 3fs (qāṭelā), 2ms (qāṭaltā), 2fs (qāṭalt), 1cs (qāṭaltī), 3cp (qāṭelū). Il concetto di binyan (struttura verbale derivata).",
    [v("קָטַל","uccise (radice modello per il paradigma)"), v("בִּנְיָן","struttura, edificio — schema verbale"), v("קַל / qal","forma verbale semplice attiva"), v("פֵּעַל / pe'al","schema verbale intensivo"), v("הִפְעִיל / hif'il","schema verbale causativo"), v("הִתְפַּעֵל / hitpa'el","schema riflessivo-reciproco")],
    "Lo studente comprende il sistema dei binyanim (schemi verbali ebraici). Coniuga qal perfetto alla 3ª, 2ª e 1ª persona. Riconosce le desinenze del perfetto qal. Capisce il concetto di radice trilitterale come unità semantica."),
  L("וְאָהַבְתָּ אֵת יְהוָה אֱלֹהֶיךָ בְּכָל-לְבָבְךָ (Deuteronomio 6,5)",
    "Lezione 6: i suffissi possessivi singolari. Si analizza we-ahavta (e amerai — wayyiqtol o vav + perfetto con valore futuro/imperativo). Si lavora sui suffissi -ka (tuo masch.) e -kha nelle varie forme. Lessico: lev (cuore), nefesh (anima), me'od (molto).",
    [v("וְאָהַבְתָּ","e amerai (vav + perf. con valore fut.)"), v("אֵת","part. oggetto diretto"), v("אֱלֹהֶיךָ","il tuo Dio (-ka = suff. 2ms)"), v("בְּכָל","con tutto (be- + kol)"), v("לְבָבְךָ","il tuo cuore (-ka suff. su lev)"), v("נַפְשְׁךָ","la tua anima"), v("מְאֹדֶךָ","la tua forza, il tuo tutto")],
    "Lo studente usa i suffissi possessivi di 2ª persona maschile singolare. Comprende vav + perfetto con valore futuro o imperativo. Legge Deuteronomio 6,5. Conosce il contesto liturgico dello Shema' completo."),
  L("בְּרֵאשִׁית — I sostantivi ebraici: genere e numero. זָכָר (maschile) e נְקֵבָה (femminile). Plurale maschile in -ִים (-im): סוּסִים (cavalli). Plurale femminile in -ֹות (-ot): תֹּורֹות (leggi).",
    "Lezione 7: il sistema nominale dell'ebraico biblico. Si lavora sul genere (maschile e femminile) e sul numero (singolare, plurale, duale). Si introducono le desinenze del plurale maschile (-im) e femminile (-ot). Il duale (per coppie naturali: manos, piedi, occhi). Irregolarità lessicali frequenti.",
    [v("זָכָר","maschile"), v("נְקֵבָה","femminile"), v("-ִים (-im)","desinenza del plurale maschile"), v("-ֹות (-ot)","desinenza del plurale femminile"), v("סוּסִים","cavalli (pl. di סוּס)"), v("יָדַיִם","mani (duale di יָד)"), v("עֵינַיִם","occhi (duale di עַיִן)")],
    "Lo studente riconosce genere e numero nei sostantivi ebraici. Forma il plurale maschile (-im) e femminile (-ot). Comprende il duale come categoria grammaticale. Identifica le irregolarità più frequenti nel plurale."),
  L("אָנֹכִי יְהוָה אֱלֹהֶיךָ אֲשֶׁר הֹוצֵאתִיךָ מֵאֶרֶץ מִצְרַיִם (Esodo 20,2 — I Comandamento)",
    "Lezione 8: il pronome relativo asher e il participio hif'il. Si analizza hotzetikha (ti ho fatto uscire) come perfetto hif'il con suffisso di 2ª pers. (-kha). Il pronome relativo asher come connettore delle proposizioni relative. Contesto: il Decalogo come testo fondamentale.",
    [v("אָנֹכִי","io (forma enfatica del pron. pers.)"), v("אֲשֶׁר","che, il quale (pronome relativo)"), v("הֹוצֵאתִיךָ","ti ho fatto uscire (hif'il perf. + suff.)"), v("מֵאֶרֶץ","dalla terra di (me- = da + eretz)"), v("מִצְרַיִם","Egitto (duale)"), v("hif'il","schema causativo del verbo ebraico")],
    "Lo studente comprende asher come pronome relativo invariabile. Riconosce lo schema hif'il come causativo. Legge Esodo 20,2. Conosce il contesto del Decalogo nella narrativa dell'Esodo."),
  L("לֹא יִהְיֶה-לְךָ אֱלֹהִים אֲחֵרִים עַל-פָּנַי (Esodo 20,3 — II Comandamento)",
    "Lezione 9: la negazione in ebraico (lo' = non per il presente/futuro; al per il vetitivo/imperativo negativo). Si analizza yihyeh come imperfetto qal di hayah. La preposizione al-panai (alla mia presenza, davanti a me). I plurali irregolari (elohim, panim).",
    [v("לֹא","non (negazione dell'indicativo)"), v("אַל","non (negazione volitiva/imperativa)"), v("יִהְיֶה","sarà (imperf. qal di ה-י-ה)"), v("אֲחֵרִים","altri (pl. di אַחֵר)"), v("עַל-פָּנַי","davanti a me (pref. + pl. panim + suff. 1cs)"), v("פָּנִים","volto, faccia (pl. tant.)")],
    "Lo studente distingue lo' da al come negazioni diverse. Usa l'imperfetto yihyeh. Comprende panim come plurale tantum. Legge il II Comandamento. Conosce la struttura del Decalogo."),
  L("מִזְמֹור לְדָוִד יְהוָה רֹעִי לֹא אֶחְסָר (Salmo 23,1)",
    "Lezione 10: i Salmi come testo letterario. Si introduce il participio qal attivo (ro'i = il mio pastore, da radice ר-ע-ה). Si lavora sui suffissi al participio (-i = mio). Contesto letterario: il Salmo 23 come testo poetico e spirituale fondamentale.",
    [v("מִזְמֹור","salmo, inno (sostantivo)"), v("לְדָוִד","di Davide (lamed autoris)"), v("רֹעִי","il mio pastore (qal part. + suff. 1cs)"), v("לֹא אֶחְסָר","non manco di nulla (imperf. qal di ח-ס-ר)"), v("ח-ס-ר","essere in mancanza, mancare"), v("participio qal","forma nominale del verbo — chi fa l'azione")],
    "Lo studente comprende il participio qal attivo come forma nominale. Usa i suffissi sul participio. Legge il Salmo 23,1. Conosce il genere salmodico nella letteratura biblica."),
  L("יְהוָה רֹעִי לֹא אֶחְסָר / בִּנְאֹות דֶּשֶׁא יַרְבִּיצֵנִי (Salmo 23,1-2)",
    "Lezione 11: il Salmo 23 continuato. Si lavora su yarbitzeni (mi fa stendere — hif'il imperfetto + suffisso 1cs). Il contrasto strutturale tra natura pastorale e presenza divina. Si introducono le metafore spaziali della poesia biblica (desheh, mayim menuhot).",
    [v("בִּנְאֹות","nei pascoli (be- + pl. niot)"), v("דֶּשֶׁא","erba fresca, pascolo verde"), v("יַרְבִּיצֵנִי","mi fa stendere (hif'il imperf. + suff. 1cs)"), v("עַל-מֵי מְנֻחֹות","presso acque tranquille"), v("מַיִם","acqua (pl. tant.)"), v("מְנֻחֹות","tranquille, riposanti (qal part. pl. femm.)")],
    "Lo studente comprende lo schema hif'il come causativo. Usa il suffisso di 1ª sing. sul verbo (-ni). Legge i versetti 1-2 del Salmo 23. Analizza le metafore pastorali della poesia biblica."),
  L("כִּי אַתָּה עִמָּדִי שִׁבְטְךָ וּמִשְׁעַנְתֶּךָ הֵמָּה יְנַחֲמֻנִי (Salmo 23,4)",
    "Lezione 12: conclusione del livello A1.1. Si lavora su ki attah immadi (perché tu sei con me) come frase nominale con avverbio. Si analizza yenahamunim (mi confortano) come pi'el imperfetto. Revisione di tutti i temi del livello: alfabeto, niqqud, qal, hif'il, suffissi, participio.",
    [v("כִּי","perché, poiché (congiunzione causale)"), v("אַתָּה","tu (pronome personale 2ms)"), v("עִמָּדִי","con me (preposizione + suff. 1cs)"), v("שֵׁבֶט","bastone, scettro"), v("מִשְׁעֶנֶת","sostegno, appoggio"), v("יְנַחֲמֻנִי","mi confortano (pi'el imperf. 3mp + suff.)"), v("pi'el","schema verbale intensivo")],
    "Lo studente consolida tutte le strutture del livello A1.1. Comprende ki come congiunzione causale. Riconosce il pi'el come schema intensivo. Legge Salmo 23,4. È pronto per il livello A1.2."),
]

# ── EBRAICO BIBLICO A1.2 — 12 lezioni ─────────────────────────────────────────
EB_A12 = [
  L("וַיֹּאמֶר אֱלֹהִים נַעֲשֶׂה אָדָם בְּצַלְמֵנוּ כִּדְמוּתֵנוּ (Genesi 1,26)",
    "Lezione 1 del livello A1.2: la creazione dell'uomo (Genesi 1,26). Si lavora su na'aseh (facciamo! — qal imperfetto coortativo 1ª pl.) come forma volitiva di noi. Si introduce il modello di declinazione be-tzalmenu (a nostra immagine) con suffisso -nu (nostro). Contesto: l'imago Dei nella teologia biblica.",
    [v("נַעֲשֶׂה","facciamo! (qal imperf. 1pl. coortativo)"), v("אָדָם","uomo, essere umano"), v("בְּצַלְמֵנוּ","a nostra immagine (be- + tzelem + -nu)"), v("צֶלֶם","immagine, effigie"), v("כִּדְמוּתֵנוּ","a nostra somiglianza (ke- + demut + -nu)"), v("דְּמוּת","somiglianza, forma")],
    "Lo studente comprende il coortativo come forma esortativa della 1ª persona. Usa il suffisso -nu (nostro) su sostantivi. Legge Genesi 1,26. Conosce il concetto teologico di imago Dei."),
  L("וַיִּבְרָא אֱלֹהִים אֶת-הָאָדָם בְּצַלְמֹו בְּצֶלֶם אֱלֹהִים בָּרָא אֹתֹו (Genesi 1,27)",
    "Lezione 2: la struttura chiastica della poesia biblica. Si analizza il chiasmo in Genesi 1,27 (bara'... tzalmo / tzelem Elohim... bara' oto). Si lavora su oto (lui — pronome oggetto indipendente). La costruzione stato costrutto (tzelem Elohim = immagine-di Elohim).",
    [v("וַיִּבְרָא","e creò (wayyiqtol qal di ב-ר-א)"), v("בְּצַלְמֹו","a sua immagine (-o suff. 3ms)"), v("אֹתֹו","lui (accusativo indipendente 3ms)"), v("stato costrutto","nomen regens + nomen rectum: tzelem Elohim"), v("chiasmo","figura retorica a specchio A-B / B-A")],
    "Lo studente comprende lo stato costrutto come genitivo implicito. Riconosce il chiasmo come figura retorica biblica. Usa il suffisso -o (suo) sui sostantivi. Legge Genesi 1,27 nella sua struttura poetica."),
  L("וַיְהִי עֶרֶב וַיְהִי בֹקֶר יֹום אֶחָד (Genesi 1,5b)",
    "Lezione 3: la formula dei giorni della creazione. Si lavora sul ritmo narrativo biblico (wayyehi erev wayyehi voqer). Si introduce erev (sera) e voqer (mattina) come coppie lessicali dell'ebraico. Il numerale cardinale echad (uno) in funzione ordinale per il primo giorno.",
    [v("עֶרֶב","sera"), v("בֹקֶר","mattina"), v("יֹום","giorno"), v("אֶחָד","uno (cardinale, qui equivale a 'primo')"), v("שֵׁנִי","secondo (ordinale)"), v("שְׁלִישִׁי","terzo"), v("numerali ebraici","cardinali e ordinali seguono pattern distinti")],
    "Lo studente usa la formula narrativa della creazione. Distingue erev (sera) da voqer (mattina). Comprende i numerali ebraici in funzione ordinale. Legge e memorizza la formula dei giorni."),
  L("וְאֵלֶּה שְׁמֹות בְּנֵי יִשְׂרָאֵל הַבָּאִים מִצְרָיְמָה (Esodo 1,1)",
    "Lezione 4: l'incipit dell'Esodo. Si lavora su ha-ba'im (che vengono — qal participio pl. con articolo come relativo). Si introduce la he directional (-ah sul sostantivo = verso: Mitzraymah = verso l'Egitto). Contesto: l'Esodo come testo narrativo fondamentale.",
    [v("וְאֵלֶּה","e questi (pronome dimostrativo pl.)"), v("שְׁמֹות","nomi (pl. di שֵׁם)"), v("בְּנֵי יִשְׂרָאֵל","figli di Israele (stato costrutto pl.)"), v("הַבָּאִים","che vengono (qal part. pl. con articolo)"), v("מִצְרָיְמָה","verso l'Egitto (he directional + Mitzrayim)"), v("-ָה directional","desinenza di moto a luogo")],
    "Lo studente comprende he directional come desinenza di moto a luogo. Usa il participio con articolo come proposizione relativa. Legge Esodo 1,1. Conosce il contesto narrativo dell'Esodo."),
  L("וְהִנֵּה אֲנִי מֵבִיא אֶת-הַמַּבּוּל מַיִם עַל-הָאָרֶץ (Genesi 6,17)",
    "Lezione 5: la storia di Noè e il diluvio. Si lavora su hinne (ecco! — particella deittica) + participio come annuncio profetico imminente. Si analizza mevi' (hif'il participio di ב-ו-א = portare, far venire). Il mabbul come termine tecnico per il diluvio.",
    [v("וְהִנֵּה","ed ecco! (particella deittica narrativa)"), v("אֲנִי","io (pronome personale 1cs)"), v("מֵבִיא","portando, (sto) portando (hif'il part. masc.)"), v("מַבּוּל","diluvio"), v("עַל-הָאָרֶץ","sulla terra"), v("hinne + part.","futuro imminente o annuncio profetico")],
    "Lo studente comprende hinne + participio come futuro imminente. Riconosce lo schema hif'il nel participio. Legge l'annuncio del diluvio in Genesi 6,17. Conosce la struttura narrativa del racconto di Noè."),
  L("לֹא תִרְצָח לֹא תִנְאָף לֹא תִגְנֹב לֹא תַעֲנֶה (Esodo 20,13-16)",
    "Lezione 6: i Comandamenti negativi e l'imperfetto come vetitivo. Si lavora su lo' + imperfetto qal come proibizione assoluta (lo' tirtza = non uccidere). Si presentano quattro radici verbali fondamentali: ר-צ-ח (uccidere), נ-א-ף (adulterare), ג-נ-ב (rubare), ע-נ-ה (testimoniare il falso).",
    [v("לֹא + יִקְטֹל","non farai (proibizione assoluta)"), v("לֹא תִרְצָח","non uccidere (ר-צ-ח = uccidere)"), v("לֹא תִנְאָף","non commettere adulterio (נ-א-ף)"), v("לֹא תִגְנֹב","non rubare (ג-נ-ב)"), v("לֹא תַעֲנֶה","non testimoniare il falso (ע-נ-ה)"), v("vetitivo","proibizione: lo' + imperfetto")],
    "Lo studente comprende lo' + imperfetto come proibizione assoluta. Conosce le quattro radici verbali dei Comandamenti. Legge Esodo 20,13-16. Analizza la struttura formulaica del Decalogo."),
  L("יְהוָה שֹׁמְרֶךָ יְהוָה צִלְּךָ עַל-יַד יְמִינֶךָ (Salmo 121,5)",
    "Lezione 7: il Salmo 121 — il Dio custode. Si lavora su shomerekha (il tuo custode — qal participio + suff. 2ms). Si analizza tzillekha (la tua ombra = protezione). Il Salmo 121 come salmo del pellegrino. Contesto: la letteratura dei pellegrinaggi nel salterio.",
    [v("שֹׁמְרֶךָ","il tuo custode (qal part. + -kha 2ms)"), v("צִלְּךָ","la tua ombra, protezione (-kha 2ms)"), v("עַל-יַד","accanto a, alla destra di"), v("יְמִינֶךָ","la tua destra (-kha 2ms su yamin)")],
    "Lo studente usa il participio qal con suffisso possessivo. Comprende tzil (ombra) come metafora di protezione. Legge Salmo 121,5. Conosce il genere dei Salmi del pellegrinaggio (Shir ha-Ma'alot)."),
  L("כִּי אֵלֶּה דִּבְרֵי הַבְּרִית אֲשֶׁר כָּרַת יְהוָה עִמָּכֶם (Esodo 34,27)",
    "Lezione 8: il concetto di berit (alleanza). Si lavora su karat berit (tagliare/stipulare un'alleanza) come espressione idiomatica fondamentale. Si introduce immakhem (con voi — preposizione im + suffisso 2ª pl.). Contesto: la teologia dell'alleanza nel Pentateuco.",
    [v("דִּבְרֵי","le parole di (stato costrutto pl. di דָּבָר)"), v("בְּרִית","alleanza, patto"), v("אֲשֶׁר","che (relativo)"), v("כָּרַת","tagliò (qal perf. di כ-ר-ת)"), v("כָּרַת בְּרִית","stipulare un'alleanza (idiom.)"), v("עִמָּכֶם","con voi (-kem suff. 2ª pl. masch.)")],
    "Lo studente comprende l'idioma karat berit. Usa il suffisso di 2ª persona plurale (-kem). Legge Esodo 34,27. Conosce il concetto teologico di berit (alleanza) come chiave del Pentateuco."),
  L("וְאֵלֶּה הַמִּשְׁפָּטִים אֲשֶׁר תָּשִׂים לִפְנֵיהֶם (Esodo 21,1)",
    "Lezione 9: il Codice del Patto (Esodo 21-23). Si lavora su tasim (metterai — qal imperfetto 2ms di ש-י-מ). Si analizza lifnehem (davanti a loro — lifne + suffisso 3mp). Il lessico giuridico: mishpatim (ordinanze, sentenze). Contesto: il diritto biblico nella tradizione orientale.",
    [v("מִשְׁפָּטִים","ordinanze, sentenze, giudizi (pl.)"), v("אֲשֶׁר","che (relativo)"), v("תָּשִׂים","metterai (qal imperf. 2ms di ש-י-מ)"), v("לִפְנֵיהֶם","davanti a loro (lifne + suff. 3mp)"), v("חֹק","statuto, legge"), v("מִצְוָה","comandamento")],
    "Lo studente riconosce il lessico giuridico biblico (mishpat, choq, mitzvah). Usa lifne + suffisso. Legge Esodo 21,1. Conosce il contesto del Codice del Patto e la sua relazione con il diritto del Vicino Oriente Antico."),
  L("יְהוָה עֹז לְעַמֹּו יִתֵּן יְהוָה יְבָרֵךְ אֶת-עַמֹּו בַשָּׁלֹום (Salmo 29,11)",
    "Lezione 10: Salmo 29 — il Dio della tempesta. Si lavora su yiten (darà — qal imperfetto di נ-ת-נ) e yevarekh (benedirà — pi'el imperfetto). Il concetto di shalom come pienezza e completezza. Il popolo come 'ammo (suo popolo — suffisso 3ms).",
    [v("עֹז","forza, potenza"), v("לְעַמֹּו","al suo popolo (-o suff. 3ms su 'am)"), v("יִתֵּן","darà (qal imperf. di נ-ת-נ, radice geminata)"), v("יְבָרֵךְ","benedirà (pi'el imperf. di ב-ר-כ)"), v("שָׁלֹום","pace, pienezza, integrità"), v("pi'el di ב-ר-כ","benedire (schema intensivo)")],
    "Lo studente comprende il pi'el come schema intensivo. Usa il suffisso possessivo di 3ª persona sing. Legge Salmo 29,11. Comprende shalom come concetto culturale e non solo pace militare."),
  L("בָּרוּךְ אַתָּה יְהוָה אֱלֹהֵינוּ מֶלֶךְ הָעֹולָם (Berakhah — formula liturgica)",
    "Lezione 11: la berakhah come formula liturgica ebraica. Si lavora su barukh (benedetto — qal participio passivo di ב-ר-כ). Si introduce melekh ha-olam (re del mondo — stato costrutto + articolo). La formula della benedizione come struttura fondamentale della preghiera ebraica.",
    [v("בָּרוּךְ","benedetto (qal pass. part. di ב-ר-כ)"), v("אַתָּה","tu (pronome personale 2ms)"), v("מֶלֶךְ","re (stato costrutto: melekh ha-olam)"), v("הָעֹולָם","il mondo, l'eternità"), v("berakhah","benedizione (formula liturgica)"), v("participio passivo","il qal può essere passivo in -u (barukh)")],
    "Lo studente comprende il participio passivo qal. Usa lo stato costrutto con articolo. Legge la formula della berakhah. Conosce la struttura della preghiera ebraica e il suo uso liturgico."),
  L("חֲזַק וֶאֱמַץ (Giosuè 1,6) — Consolidamento A1.2 e preparazione all'A2",
    "Lezione 12: revisione e consolidamento del livello A1.2. La formula hazaq ve-ematz (sii forte e coraggioso) come imperativo qal. Si ripassa: qal, pi'el, hif'il, participi, suffissi, stati costrutti, wayyiqtol, vetitivo. Proiezione verso il livello A2: testi narrativi estesi, profeti, poesia.",
    [v("חֲזַק","sii forte! (qal imperativo di ח-ז-ק)"), v("אֱמַץ","sii coraggioso! (qal imperativo di א-מ-צ)"), v("וֶ-","e (vav copulativo prima di sheva)"), v("revisione","qal, pi'el, hif'il, participi, wayyiqtol"), v("profezia","genere letterario dell'A2")],
    "Lo studente consolida tutte le strutture grammaticali dell'A1.2. Comprende la formula di incoraggiamento hazaq ve-ematz. Riconosce i principali schemi verbali. È pronto per il livello A2."),
]

# ── EBRAICO BIBLICO A2 — 16 lezioni ───────────────────────────────────────────
EB_A21 = [
  L("וַיֵּצֵא יַעֲקֹב מִבְּאֵר שָׁבַע וַיֵּלֶךְ חָרָנָה (Genesi 28,10)",
    "Lezione 1 del livello A2: la partenza di Giacobbe per Haran. Si lavora su wa-yetze (e partì — wayyiqtol qal di י-צ-א) e wa-yelekh (e andò — wayyiqtol di ה-ל-כ). Le radici 'deboli' (con yod o vav iniziale) e i loro pattern al wayyiqtol. Lessico del viaggio e dello spostamento.",
    [v("וַיֵּצֵא","e partì (wayyiqtol qal di י-צ-א, radice yod)"), v("מִבְּאֵר שָׁבַע","da Beersheba (da + stat. costr.)"), v("וַיֵּלֶךְ","e andò (wayyiqtol di ה-ל-כ, radice lamed-he)"), v("חָרָנָה","verso Haran (he directional)"), v("radici deboli","radici con gutturali o lettere deboli")],
    "Lo studente comprende il wayyiqtol delle radici deboli (yod iniziale, lamed-he). Usa he directional. Legge Genesi 28,10. Conosce il contesto della saga patriarcale."),
  L("וַיַּחֲלֹם וְהִנֵּה סֻלָּם מֻצָּב אַרְצָה (Genesi 28,12)",
    "Lezione 2: il sogno di Giacobbe (Genesi 28,12). Si lavora su wa-yakhalom (sognò — wayyiqtol qal di ח-ל-מ) e sulam (scala — sostantivo raro). Si analizza mutzav (piantata — qal passivo participio di נ-צ-ב). Hinne come particella della visione onirica.",
    [v("וַיַּחֲלֹם","e sognò (wayyiqtol qal di ח-ל-מ)"), v("סֻלָּם","scala, rampa (hapax legomenon)"), v("מֻצָּב","piantata, eretta (qal pass. part. di נ-צ-ב)"), v("אַרְצָה","verso la terra (he directional)"), v("hapax legomenon","parola attestata una sola volta nel testo biblico")],
    "Lo studente analizza il participio passivo qal. Comprende hinne come marcatore della visione. Legge Genesi 28,12. Conosce il concetto di hapax legomenon nella critica testuale."),
  L("אָנֹכִי יְהוָה אֱלֹהֵי אַבְרָהָם אָבִיךָ וֵאלֹהֵי יִצְחָק (Genesi 28,13)",
    "Lezione 3: la promessa divina a Giacobbe. Si lavora sulla formula di auto-presentazione (anokhi YHWH Elohei...) come struttura teofanica. Si analizza lo stato costrutto con nomi propri (Elohei Avraham = il Dio di Abramo). Lessico della rivelazione.",
    [v("אָנֹכִי","io (forma enfatica, tipica delle rivelazioni)"), v("אֵל / אֱלֹהִים","El / Elohim — nomi divini"), v("אֱלֹהֵי + nome","il Dio di... (stato costrutto)"), v("אָבִיךָ","tuo padre (-kha suff. 2ms)"), v("teofania","rivelazione diretta del divino")],
    "Lo studente comprende la formula teofanica anokhi YHWH. Usa lo stato costrutto con nomi propri. Legge Genesi 28,13. Analizza la struttura della promessa divina nella narrativa biblica."),
  L("וְהִנֵּה אָנֹכִי עִמָּךְ וּשְׁמַרְתִּיךָ בְּכֹל אֲשֶׁר-תֵּלֵךְ (Genesi 28,15)",
    "Lezione 4: la promessa di protezione. Si lavora su u-shemartikha (e ti custodirò — qal perf. con vav + suff. 2ms) come forma del futuro enfatico. Si introduce be-khol asher (in ogni luogo in cui) come relativo onnicomprensivo.",
    [v("וּשְׁמַרְתִּיךָ","e ti custodirò (vav perf. + suff. -kha)"), v("בְּכֹל אֲשֶׁר","in tutto ciò che, ovunque"), v("תֵּלֵךְ","tu vada (qal imperf. di ה-ל-כ 2ms)"), v("vav + perfetto","valore futuro o consecutivo")],
    "Lo studente comprende il vav + perfetto come futuro enfatico o consecutivo. Usa be-khol asher come relativo onnicomprensivo. Legge Genesi 28,15. Analizza la struttura sintattica della promessa divina."),
  L("יְשַׁלֵּם יְהוָה פָּעֳלֵךְ וּתְהִי מַשְׂכֻּרְתֵּךְ שְׁלֵמָה (Rut 2,12)",
    "Lezione 5: il libro di Rut. Si lavora su yeshallam (ricompensi — pi'el iussivo di ש-ל-מ). Si introduce la femminilizzazione del suffisso -ekh (tuo/tua per il femm.). Contesto letterario: Rut come testo narrativo di alta qualità stilistica e veicolo di inclusività.",
    [v("יְשַׁלֵּם","ricompensi! (pi'el iussivo di ש-ל-מ)"), v("פָּעֳלֵךְ","la tua azione, il tuo lavoro (-ekh suff. 2fs)"), v("תְהִי","sia (iussivo qal femm. di ה-י-ה)"), v("מַשְׂכֻּרְתֵּךְ","la tua ricompensa (-ekh suff. 2fs)"), v("שְׁלֵמָה","completa, intera (femm. di shalem)"), v("-ֵךְ / -ָךְ","suffisso 2ª pers. femminile sing.")],
    "Lo studente comprende il pi'el iussivo come benedizione. Usa il suffisso di 2ª persona femminile (-ekh). Legge Rut 2,12. Conosce il genere narrativo del libro di Rut."),
  L("וַיֹּאמֶר הָמָן... לָמָּה לֹא-אַתָּה כֹּרֵעַ לִי (Ester 3,2 adatt.)",
    "Lezione 6: il libro di Ester. Si lavora su korea' (si inchina — qal participio di כ-ר-ע) come stato continuativo. Si introduce lammah (perché?) come interrogativo diretto. Contesto narrativo: il libro di Ester come racconto diasporico e commedia di potere.",
    [v("לָמָּה","perché? (interrogativo diretto)"), v("כֹּרֵעַ","si inchinano (qal part. di כ-ר-ע)"), v("הָמָן","Haman (il villain della storia)"), v("לִי","a me (preposizione le + suff. 1cs)"), v("participio come durativo","esprime azione in corso o abitudinale")],
    "Lo studente comprende lammah come interrogativo diretto. Usa il participio come durativo. Legge un passo da Ester. Conosce il genere narrativo diasporico del libro di Ester."),
  L("כָּל-הַנְּשָׁמָה תְּהַלֵּל יָהּ הַלְלוּ-יָהּ (Salmo 150,6)",
    "Lezione 7: l'ultimo versetto dell'ultimo Salmo. Si lavora su tehalel (lodino — pi'el imperfetto) come forma esortativa. Si introduce Yah come forma abbreviata del tetragramma. Halleluyah come formula liturgica onomatopeica. Revisione dei Salmi.",
    [v("כָּל-הַנְּשָׁמָה","ogni essere vivente (kol + neshama)"), v("תְּהַלֵּל","lodi! (pi'el imperf. iussivo di ה-ל-ל)"), v("יָהּ","Yah (forma abbreviata del tetragramma)"), v("הַלְלוּ-יָהּ","lodate YHWH! (hallelu + Yah)"), v("ה-ל-ל","lodare (radice geminata, III-geminate)")],
    "Lo studente comprende il pi'el delle radici geminate. Usa il iussivo come esortazione. Legge Salmo 150,6. Comprende Halleluyah come formula liturgica e la sua origine ebraica."),
  L("אֵיכָה יָשְׁבָה בָדָד הָעִיר (Lamentazioni 1,1)",
    "Lezione 8: le Lamentazioni. Si lavora su ekhah (come!, come mai! — avverbio di meraviglia dolente) e yashevah (siede — qal perfetto femm. sing. di י-ש-ב). Il genere letterario della qinah (lamento) e il suo metro speciale (3+2). Contesto: la distruzione di Gerusalemme (587 a.C.).",
    [v("אֵיכָה","come!, come mai! (avv. di lamento)"), v("יָשְׁבָה","siede (qal perf. 3fs di י-ש-ב)"), v("בָּדָד","in solitudine, sola (avv.)"), v("הָעִיר","la città"), v("qinah","lamento, elegia (metro 3+2)"), v("kinah meter","metro 3+2 tipico del lamento biblico")],
    "Lo studente comprende il metro della qinah (3+2). Usa ekhah come avverbio di lamento. Legge Lamentazioni 1,1. Conosce il contesto storico della distruzione di Gerusalemme."),
  L("כִּי חָשַׁבְתִּי מַחֲשָׁבֹות שָׁלֹום וְלֹא לְרָעָה (Geremia 29,11)",
    "Lezione 9: Geremia e il messaggio alla diaspora. Si lavora su hashavti (ho pensato — qal perfetto di ח-ש-ב) e la costruzione mahshavot shalom (pensieri di pace). Si introduce ki come congiunzione causale asseverativa. Contesto: la lettera di Geremia agli esiliati.",
    [v("כִּי","poiché, indeed (asseverativo)"), v("חָשַׁבְתִּי","ho pensato (qal perf. 1cs di ח-ש-ב)"), v("מַחֲשָׁבֹות","pensieri, piani (pl. di מַחֲשָׁבָה)"), v("שָׁלֹום","pace, prosperità, benessere"), v("לְרָעָה","per il male (le + ra'ah)"), v("manoscritto Q","codici del Mar Morto come fonte testuale")],
    "Lo studente comprende ki in funzione asseverativa. Usa stato costrutto con astratti. Legge Geremia 29,11. Conosce la lettera di Geremia agli esiliati e il contesto della Babilonia."),
  L("עֵינַי כִּלּוּ אֶל-יְשׁוּעָתֶךָ (Salmo 119,123)",
    "Lezione 10: il Salmo 119 — il più lungo del Salterio. Si lavora su killu (hanno consumato — pi'el perfetto 3cp di כ-ל-ה). Il Salmo 119 come poema acrostico alfabetico (22 strofe × 8 versi, ogni strofa inizia con una lettera dell'alfabeto). El (verso, direzione) come preposizione.",
    [v("עֵינַי","i miei occhi (dual + suff. 1cs)"), v("כִּלּוּ","hanno consumato (pi'el perf. 3cp di כ-ל-ה)"), v("אֶל","verso (preposizione di direzione)"), v("יְשׁוּעָתֶךָ","la tua salvezza (-kha suff. 2ms)"), v("acrostico","Salmo 119: ogni strofa inizia con lettera dell'alef-bet")],
    "Lo studente comprende il pi'el delle radici lamed-he. Usa il suffisso del duale. Legge Salmo 119,123. Conosce la struttura acrostica del Salmo 119."),
  L("אֱמֶת וּמִשְׁפָּט שָׁלֹום שִׁפְטוּ בְּשַׁעֲרֵיכֶם (Zaccaria 8,16)",
    "Lezione 11: Zaccaria e la profezia post-esilica. Si lavora su shiftu (giudicate — qal imperativo pl. di ש-פ-ט). Si introduce be-sha'areykem (nelle vostre porte — preposizione + stato costrutto + suff. 2pl). Il concetto di emet u-mishpat shalom (verità, giustizia e pace) come triade etica.",
    [v("אֱמֶת","verità, fedeltà"), v("מִשְׁפָּט","giustizia, giudizio"), v("שִׁפְטוּ","giudicate! (qal imper. pl. di ש-פ-ט)"), v("בְּשַׁעֲרֵיכֶם","nelle vostre porte (-kem suff. 2mp)"), v("sha'ar","porta (della città, luogo del giudizio)")],
    "Lo studente comprende l'imperativo qal plurale. Usa il suffisso di 2ª persona plurale (-kem). Legge Zaccaria 8,16. Conosce il contesto della profezia post-esilica."),
  L("הַגִּידוּ בַגֹּויִם כְּבֹודֹו (Salmo 96,3)",
    "Lezione 12: Salmo 96 — il Dio creatore-re. Si lavora su haggidu (annunciate — hif'il imperativo pl. di נ-ג-ד). Si analizza kevodo (la sua gloria — kavod + suff. 3ms). Il Salmo 96 come inno all'universalità del regno di YHWH. Preparazione al B1.",
    [v("הַגִּידוּ","annunciate! (hif'il imper. pl. di נ-ג-ד)"), v("גֹּויִם","nazioni, popoli (pl. di גֹּוי)"), v("כְּבֹודֹו","la sua gloria (-o suff. 3ms su kavod)"), v("כָּבֹוד","gloria, peso, presenza divina"), v("hif'il imperativo","comando causativo: fate annunciare")],
    "Lo studente comprende l'imperativo hif'il. Usa il suffisso di 3ª persona sing. Legge Salmo 96,3. Consolida tutte le strutture del livello A2. È pronto per il B1 e la lettura autonoma."),
  L("חִזְקוּ וְיַאֲמֵץ לְבַבְכֶם (Salmo 31,25) — Revisione",
    "Lezione 13: revisione intermedia dell'A2. Si ripassano wayyiqtol, stati costrutti, suffissi di tutte le persone, binyanim (qal, pi'el, hif'il), participi, infiniti. La formula hizqu ve-ya'ametz levavkhem (siate forti e coraggio al vostro cuore) come sintesi del livello.",
    [v("חִזְקוּ","siate forti! (qal imper. pl.)"), v("יַאֲמֵץ","si irrobustisca (pi'el iussivo di א-מ-צ)"), v("לְבַבְכֶם","il vostro cuore (-kem suff. 2mp)")],
    "Lo studente consolida le strutture principali dell'A2. Riconosce i binyanim principali. Comprende la grammatica della profezia e della poesia biblica. Si prepara alla seconda metà del livello A2."),
  L("הֲלֹוא כֹה דִּבֶּר יְהוָה אֱלֹהֵי יִשְׂרָאֵל (1 Re 14,7 adatt.)",
    "Lezione 14: la formula profetica. Si lavora su ha-lo' (non forse? — interrogativo retorico che attende risposta affermativa). Si analizza dibber (parlò — pi'el perfetto di ד-ב-ר, intensivo frequentativo). Struttura standard del messaggio profetico: formula di invio + formula del messaggero.",
    [v("הֲלֹוא","non è forse che? (interr. retorica affermativa)"), v("כֹּה","così, in questi termini"), v("דִּבֶּר","parlò (pi'el perf. di ד-ב-ר)"), v("כֹּה אָמַר יְהוָה","così ha detto YHWH (formula del messaggero)"), v("pi'el di ד-ב-ר","parlare con autorità/insistenza")],
    "Lo studente comprende ha-lo' come interrogativa retorica. Analizza il pi'el di dabar come parlare profetico. Legge un passo della formula del messaggero. Conosce la struttura del discorso profetico."),
  L("וְשַׁבְתָּ עַד-יְהוָה אֱלֹהֶיךָ (Deuteronomio 30,2)",
    "Lezione 15: la teologia del ritorno (teshuvah). Si lavora su ve-shavta (e ritornerai — vav + qal perfetto di ש-ו-ב). Il concetto di teshuvah (ritorno, pentimento) come categoria teologica centrale. Il prefisso ad- (fino a) come preposizione di arrivo.",
    [v("וְשַׁבְתָּ","e ritornerai (vav + qal perf. 2ms di ש-ו-ב)"), v("עַד-","fino a, fino a raggiungere"), v("teshuvah","ritorno, conversione (da ש-ו-ב)"), v("ש-ו-ב","tornare (radice della conversione)"), v("vav + perfetto con valore fut.","valore futuro o imperativo enfatico")],
    "Lo studente comprende vav + perfetto con valore futuro. Analizza la radice sh-v-b (tornare). Legge Deuteronomio 30,2. Comprende il concetto teologico di teshuvah."),
  L("שׁוּבָה יִשְׂרָאֵל עַד יְהוָה אֱלֹהֶיךָ (Osea 14,2) — Revisione finale A2",
    "Lezione 16 — conclusiva dell'A2: Osea e il ritorno definitivo. Si consolida l'imperativo qal (shuvah). Si fa un riepilogo dell'intero percorso A1-A2: alfabeto, niqqud, radici, binyanim, sintassi della frase biblica, generi letterari (narrativa, poesia, profezia, salmo). Proiezione verso il B1.",
    [v("שׁוּבָה","ritorna! (qal imper. con he paragogica)"), v("he paragogica","-ah sull'imperativo: enfasi o stile arcaico"), v("הושע","Osea (profeta dell'VIII sec.)"), v("riepilogo A1-A2","radici, binyanim, wayyiqtol, suffissi, stati costrutti")],
    "Lo studente consolida tutto il percorso A1-A2 dell'ebraico biblico. Comprende he paragogica sull'imperativo. Legge Osea 14,2. È in grado di leggere testi biblici brevi con supporto e si prepara al B1."),
]

# ── IDS ────────────────────────────────────────────────────────────────────────
IDS_EB_A11 = [
  "011fd3ca-9f39-417c-8ede-4423c4301af1",
  "431f0c21-52a0-4e4b-8ae9-f71710aba29f",
  "ebbad7b2-bddc-40bc-b9ef-6e44301f324a",
  "eb084057-2075-449f-93cb-893c16b935c9",
  "55215ae7-aa53-4af1-a41d-d3495b1a33fa",
  "27f9d49c-7544-465c-87e0-34d814486c8c",
  "1e43ae2f-862e-48bd-966c-363749193a3c",
  "6cf88a46-1285-4539-9f01-6beda53f4425",
  "d72b78df-0315-4613-9f39-249d19ff1c64",
  "f918c3e8-c235-447f-975e-92fb0b8a4fbf",
  "8fd133cd-6014-48ae-b04b-17ffed3005fe",
  "350712b8-c55e-41ea-aa5d-a63dd9f665d4",
]
IDS_EB_A12 = [
  "87ed38af-0a07-4e25-881d-b995a2594a33",
  "b20d9396-b819-4d50-a386-ca34e91fca8a",
  "60ade0de-3a9c-43ad-b1fa-a9addf308e3d",
  "a6501614-1a1f-473c-af8a-615023e76b0a",
  "18d35c06-8a74-4bb1-8e6c-54e07d16b737",
  "3d0edcfe-445c-4e36-9508-e0a9558552aa",
  "1a9fdcc2-4436-4388-970d-1b8091890e59",
  "2a140fb3-d463-49ba-b601-f2f930135ad1",
  "dca21fa3-b008-4f9e-8d50-a4f8f2699cb9",
  "8ed71066-2535-44a7-b14c-3696077c7bf2",
  "402f2220-7bcc-43dd-a99c-e7ec835b67d7",
  "8ddafc3e-482f-4b43-8cb1-b70060092903",
]
IDS_EB_A21 = [
  "20726425-43b8-40ff-873f-280006630c41",
  "37d672b8-844a-4c68-bdeb-57110b4fcd76",
  "8acd004e-c84d-4cf2-aba3-2abd7fa61d1b",
  "d5d9520f-9758-4135-bfe2-7d2855a0be90",
  "ccb158a5-0b61-4da6-8248-7acbc7eb18c6",
  "e0c6903d-5ba9-4921-ac96-632d8bb83e5f",
  "174116d0-d49d-4ab0-84fb-113fbaaf6664",
  "b1f7d8e9-bde3-4cb2-9433-8bd1760dc549",
  "f1b53c84-f415-4789-8e8e-24326418963b",
  "e0c94781-1872-4479-afd6-f1191cec5f41",
  "5c54eaf5-4f21-496e-85a5-3d54cd0f3e5a",
  "e8399869-b377-43ab-a874-26b8269bd1c2",
  "9350c5e4-2715-4fc6-95d9-1620638bc5c3",
  "aadf517c-24fd-42de-b52d-54a335a27966",
  "e15208d8-0278-4591-af14-c27318a67899",
  "ecc5faf3-32b6-4e57-8e83-29da338149d7",
]

# ── EGIZIANO A1.1 — 18 lezioni ─────────────────────────────────────────────────
# Egyptian: content focuses on cultural/historical context since hieroglyphics
# require visual rendering. textFragment uses transliteration + key signs described.
EG_TEMPLATE = lambda n, topic, tf, cs, kv, lo: L(tf, cs, kv, lo)

EG_A11_DATA = [
  ("alfabeto uniliterale", "𓄿 (aleph) 𓇋 (i) 𓏭 (y) 𓂝 (a) 𓅱 (w) 𓃀 (b) 𓊪 (p) 𓆑 (f) 𓅓 (m)",
   "Lezione 1: introduzione all'egiziano geroglifico. Il sistema di scrittura egiziano è triplice: fonogrammi (suoni), logogrammi (parole) e determinativi (categorie semantiche). I 24 segni uniletterali sono la base: si impara a riconoscerli, traslitterarli e pronunciarli.",
   [v("fonogramma","segno che rappresenta un suono"), v("logogramma","segno che rappresenta una parola intera"), v("determinativo","segno semantico muto alla fine di una parola"), v("uniliterale","segno di un solo suono consonantico"), v("𓄿 (aleph)","consonante gutturale"), v("𓅓 (m)","la civetta — segno di m"), v("traslitterazione","sistema per trascrivere geroglifici in caratteri latini")],
   "Lo studente riconosce i primi 8 segni uniletterali. Comprende la triplice natura del sistema geroglifico. Traslittera parole semplici. Legge da destra a sinistra o sinistra a destra seguendo la direzione dei segni."),
  ("alfabeto 2", "𓇼 (n) 𓂋 (r) 𓉔 (h) 𓎛 (H) 𓐍 (x) 𓄡 (X) 𓊃 (z) 𓋴 (s)",
   "Lezione 2: i restanti segni uniletterali. Si introducono le consonanti della seconda metà dell'alfabeto egiziano: n, r, h, H (h aspirata), x (kh), X (kh enfatica), z, s. La distinzione tra varianti della stessa consonante è fondamentale per la lettura.",
   [v("𓇼 (n)","la linea d'acqua — suono n"), v("𓂋 (r)","la bocca — suono r"), v("𓉔 (h)","la capanna — suono h"), v("𓎛 (H)","la corda annodata — h fortis"), v("𓐍 (x)","il setaccio — suono kh"), v("𓊃 (z)","il chiavistello — suono z o s"), v("𓋴 (s)","il tessuto — suono s")],
   "Lo studente completa l'alfabeto uniletterale (24 segni). Distingue varianti della stessa consonante. Traslittera parole di base. Riconosce la direzione di lettura dai segni animali (guardano verso l'inizio della riga)."),
  ("sistema numerico", "𓏤 = 1, 𓎆 = 10, 𓍢 = 100, 𓆼 = 1000, 𓂭 = 10.000, 𓆐 = 100.000, 𓁨 = 1.000.000",
   "Lezione speciale sulla decifrazione: Jean-François Champollion e la Stele di Rosetta (1822). Si racconta la storia della decifrazione: il testo trilingue (geroglifico, demotico, greco), il nome di Cleopatra come chiave, la scoperta del sistema misto. I numeri egiziani come primo sistema decimale.",
   [v("Stele di Rosetta","iscrizione trilingue trovata a Rosetta nel 1799"), v("Champollion","decifratore dei geroglifici (1822)"), v("cartuccia","cornice ovale che contiene il nome reale"), v("geroglifico","scrittura sacra (hiero-glyph = incisione sacra in gr.)"), v("demotico","scrittura corsiva popolare egiziana"), v("additivo","il sistema numerico egiziano somma i simboli")],
   "Lo studente conosce la storia della decifrazione. Legge numeri egiziani semplici. Riconosce la cartuccia reale. Comprende il sistema misto (fonografico + logografico + semantico)."),
  ("bilitterali", "𓆎 (ms) 𓌀 (wn) 𓌃 (mr) 𓌀 (nb) 𓅭 (zA) 𓊹 (nTr)",
   "Lezione 3: i segni bilitterali. Mentre i 24 segni uniletterali rappresentano un solo suono, i segni bilitterali ne rappresentano due. Si impara a riconoscere e traslitterare i principali segni bilitterali. La combinazione di bilitterali e unilitterali come complemento fonetico.",
   [v("bilitterale","segno che rappresenta due consonanti"), v("𓌀 (wn)","il coniglio — suono wn"), v("𓌃 (mr)","il canale — suono mr"), v("𓆎 (ms)","tre volpi — suono ms"), v("complemento fonetico","unilitterale che ripete l'ultima consonante del bilitterale"), v("𓊹 (nTr)","segno di 'dio, divino'")],
   "Lo studente riconosce i principali segni bilitterali. Comprende il sistema del complemento fonetico. Traslittera parole con bilitterali. Usa nTr come determinativo del campo semantico divino."),
  ("sostantivi e articoli", "𓂋𓏤𓀀 (r = bocca), 𓊹𓏤 (nTr = dio), 𓋹𓈖𓐍 (anx = vita)",
   "Lezione 4: i sostantivi dell'egiziano medio. I sostantivi maschili terminano in consonante, i femminili in -t. Il determinativo alla fine della parola indica la categoria semantica. Si introduce 𓋹 ankh come segno della vita. Il concetto di stato assoluto e stato costrutto.",
   [v("𓋹 (anx)","vita (il segno ankh)"), v("-t femminile","il punto diacritico per il femminile"), v("determinativo","segno muto che chiarisce il significato"), v("𓀀 (uomo)","determinativo per parole maschili umane"), v("𓀁 (donna)","determinativo per parole femminili"), v("stato costrutto","genitivo diretto senza preposizione")],
   "Lo studente distingue maschile e femminile in egiziano. Comprende la funzione del determinativo. Legge parole con segno ankh. Conosce i principali determinativi semantici."),
  ("verbi base", "𓂝𓋴𓂻 (sDm = sentire, ascoltare), 𓂝𓏛 (wD = ordinare), 𓈖𓃀 (nb = signore)",
   "Lezione 5: il sistema verbale dell'egiziano medio. Il verbo non ha tempi verbali nel senso greco-latino: l'aspetto (azione compiuta/non compiuta) è il parametro centrale. Si introduce sDm come verbo-modello (sentire, ascoltare). La forma sDm=f (lui sente) come paradigma di base.",
   [v("sDm=f","lui sente (paradigma verbale base)"), v("=f","suffisso pronominale 3ms"), v("aspetto","compiuto vs. non compiuto (non tempo)"), v("𓂝𓋴𓂻 (sDm)","sentire, udire (radice trilitterale)"), v("suffisso pronominale","il soggetto è espresso come suffisso del verbo")],
   "Lo studente comprende il sistema aspettuale del verbo egiziano. Usa la forma sDm=f come paradigma. Riconosce i suffissi pronominali. Distingue aspetto compiuto da non compiuto."),
  ("frasi nominali", "nTr nfr (dio buono), nb tAwy (signore delle Due Terre), anx wDA snb (vita, prosperità, salute)",
   "Lezione 6: la frase nominale egiziana. La predicazione nominale non usa copula: nTr nfr significa letteralmente 'un dio buono' ma funziona come 'il dio è buono'. Si introduce nb tAwy come titolo reale. La triade augurale anx wDA snb.",
   [v("nTr nfr","il dio buono (epiteto reale, es. Tutankhamon)"), v("nb","signore (sostantivo)"), v("tAwy","le Due Terre (Egitto Alto + Basso)"), v("anx wDA snb","vita, prosperità, salute (formula augurale)"), v("frase nominale","predicazione senza copula"), v("nfr","bello, buono, perfetto (aggettivo comune)")],
   "Lo studente comprende la frase nominale senza copula. Usa titoli regi fondamentali. Legge la triade augurale anx wDA snb. Conosce il significato di nTr nfr come epiteto reale."),
  ("pronomi", "ink (io), ntk (tu masch.), nts (tu femm.), ntf (lui), nts (lei), inn (noi), ntn (voi), sn (loro)",
   "Lezione 7: i pronomi indipendenti e suffissi dell'egiziano. I pronomi indipendenti si usano come soggetto enfatico. I pronomi suffissi si agganciano ai verbi, sostantivi e preposizioni. Il sistema pronomiale è fondamentale per decodificare la sintassi.",
   [v("ink","io (pron. indip. 1cs)"), v("ntk","tu (pron. indip. 2ms)"), v("ntf","lui (pron. indip. 3ms)"), v("=i","mi, mio (suff. 1cs)"), v("=k","ti, tuo (suff. 2ms)"), v("=f","lo, suo (suff. 3ms)"), v("pron. suffisso","si aggiunge al verbo o al sostantivo")],
   "Lo studente usa i pronomi indipendenti e suffissi. Distingue 1ª, 2ª e 3ª persona. Legge frasi con pronomi. Comprende la differenza tra pronome indipendente (enfatico) e suffisso (normale)."),
  ("preposizioni", "m (in), n (per, a), r (verso), Hr (su), xnt (davanti), m-bAH (davanti a)",
   "Lezione 8: le preposizioni egiziane. Le preposizioni si scrivono prima del complemento e spesso si combinano con suffissi pronominali. Si lavora sulle preposizioni di stato in luogo (m = in) e di moto (r = verso). Contesto: la descrizione del tempio e dei suoi spazi.",
   [v("m","in, come, da (prep. polivalente)"), v("n","per, a, di (dativo/genitivo)"), v("r","verso, a (moto a luogo)"), v("Hr","su, sopra (hr + suff.)"), v("xnt","davanti, di fronte"), v("m-bAH","in presenza di, davanti")],
   "Lo studente usa le preposizioni fondamentali dell'egiziano. Combina preposizioni con suffissi pronominali. Legge frasi di luogo. Conosce il lessico degli spazi sacri egiziani."),
  ("testi reali", "𓊹𓄿𓄿𓀭 (Amon-Ra), 𓇳𓄿𓃭𓏤 (Ra), 𓐠𓂝𓄿𓏛𓏏𓏤 (Maat)",
   "Lezione 9: le divinità egiziane e i loro nomi. Si leggono i nomi delle principali divinità: Ra (sole), Amon (il nascosto), Maat (l'ordine cosmico), Thoth (scrittura e sapienza), Iside, Osiride. I nomi divini nei testi religiosi come primo contesto di lettura.",
   [v("Ra","il sole (dio principale dell'Antico Egitto)"), v("Amon","il nascosto (dio di Tebe, poi Amon-Ra)"), v("Maat","verità, giustizia, ordine cosmico"), v("Thoth","dio della scrittura e sapienza"), v("Iside (Ast)","dea madre, magia"), v("Osiride (Wsir)","dio dei morti e resurrezione")],
   "Lo studente legge i nomi delle divinità principali. Riconosce i determinativi divini. Conosce la funzione di Maat come principio cosmologico. Comprende il pantheon egiziano."),
  ("formula dell'offerta", "Htp di nsw (offerta che il re fa): Htp di nsw Amon Ra nb nswt tAwy",
   "Lezione 10: la formula dell'offerta (Htp di nsw). È la formula più comune nell'epigrafia funeraria egiziana: 'Un'offerta che il re fa (al dio X) affinché doni pane, birra, buoi, oche... al ka di (nome del defunto)'. Si analizza la struttura sintattica della formula.",
   [v("Htp di nsw","offerta che il re fa (formula funeraria)"), v("Htp","offerta, pace, soddisfazione"), v("nsw","re (titolo reale)"), v("kA","ka, il doppio spirituale"), v("invocazione","formula per il defunto nei testi tombali"), v("formula funeraria","testo standard sulle stele e nei sarcofagi")],
   "Lo studente legge la formula Htp di nsw. Comprende il concetto di kA (ka). Riconosce le formule funerarie standard. Conosce il contesto delle stele tombali egiziane."),
  ("Libro dei Morti", "Capitolo 125: il Giudizio dei Morti e la pesatura del cuore. Il testo dice: ib=i n=i m xrt-nTr (il mio cuore è per me nel regno dei morti)",
   "Lezione 11: il Libro dei Morti — cap. 125. La scena del giudizio: il cuore (ib) del defunto viene pesato contro la piuma di Maat. La confessione negativa. Il testo dell'egiziano è tra i più importanti della letteratura religiosa del mondo antico.",
   [v("Libro dei Morti (r nw prt m hrw)","il Libro dell'Uscire durante il Giorno"), v("ib","cuore (sede dell'intelletto e della moralità)"), v("Anubi (Inpw)","dio che sorveglia la pesatura"), v("piuma di Maat","il contrappeso della pesatura"), v("confessione negativa","lista di peccati non commessi"), v("Ammat","il divoratore dei cuori impuri")],
   "Lo studente comprende la scena del giudizio dei morti. Legge frasi del capitolo 125. Conosce il concetto di ib (cuore) nella teologia egiziana. Comprende la struttura del Libro dei Morti."),
  ("Testi delle Piramidi", "I Testi delle Piramidi (PT): più antico corpus religioso scritto. wnn=f anx wDA snb",
   "Lezione 12: i Testi delle Piramidi (2400-2300 a.C.). Sono il più antico corpus religioso scritto al mondo. Si trovano sulle pareti delle piramidi della V-VI dinastia. Si legge wnn=f (lui esiste — forma durativa di wn). La resurrezione del faraone come tema centrale.",
   [v("Testi delle Piramidi","più antico corpus religioso scritto (V-VI din.)"), v("wnn=f","egli esiste (form. durativa di wn)"), v("wn","essere, esistere"), v("piramide di Unas","prima piramide con Testi delle Piramidi"), v("resurrezione reale","il re risorge come stella circumpolare")],
   "Lo studente conosce i Testi delle Piramidi come corpus più antico. Comprende wnn=f come forma durativa. Legge frasi dai Testi delle Piramidi. Capisce il contesto della resurrezione reale nella teologia egiziana."),
  ("geroglifici cartuccia", "Nomi reali nelle cartucce: Ramses II = Ra-ms-sw, Cleopatra = qLjwpAdra",
   "Lezione 13: la cartuccia reale e i nomi dei faraoni. Si legge la cartuccia di Ramses II (Ra + ms + sw = Ra lo ha generato). La cartuccia di Cleopatra come chiave della decifrazione di Champollion. Il serekh come forma più antica della cartuccia.",
   [v("cartuccia (Sn)","cornice ovale che racchiude il nome reale"), v("Ramses II","Ra-ms-sw = Ra lo ha generato"), v("Cleopatra","qLjwpAdra — nome greco traslitterato"), v("serekh","forma arcaica della cartuccia (facciata di palazzo)"), v("prenome","nome di incoronazione del faraone"), v("nome proprio","nome di nascita del faraone")],
   "Lo studente legge le cartucce di Ramses II e Cleopatra. Comprende la struttura del nome reale. Analizza il ruolo della cartuccia nella decifrazione. Conosce prenome e nome proprio del faraone."),
  ("grammatica avanzata", "sDm.n=f (forma del perfetto narrativo), iw=f Hr sDm (lui sta ascoltando — forma progressiva)",
   "Lezione 14: le forme verbali principali dell'egiziano medio. Si introduce sDm.n=f come forma del perfetto narrativo (lui ha ascoltato). Si analizza iw=f Hr sDm come costruzione progressiva (lui sta ascoltando). Il sistema verbale egiziano come sistema aspettuale.",
   [v("sDm.n=f","lui ha ascoltato (perfetto narrativo)"), v(".n","morfema del perfetto"), v("iw=f Hr sDm","lui sta ascoltando (progressivo)"), v("iw","particella iniziale di frase verbale"), v("Hr + inf.","stato progressivo dell'azione"), v("aspetto compiuto vs. non compiuto","il parametro base del verbo egiziano")],
   "Lo studente comprende sDm.n=f come perfetto narrativo. Analizza iw=f Hr sDm come progressivo. Distingue aspetto compiuto da non compiuto. Riconosce le principali forme verbali dell'egiziano medio."),
  ("testi autobiografici", "Stele di Amenhotep: ink s nfr xw n kA=f (io sono un uomo che protegge il suo ka)",
   "Lezione 15: le autobiografie tombali. Le stele funerarie contengono spesso una breve autobiografia del defunto che elenca le sue virtù (confessione positiva). Si lavora su ink s nfr (io sono un uomo buono). Lessico delle virtù: mAa-xrw (giusto di voce = defunto glorificato).",
   [v("ink s nfr","io sono un uomo buono/retto"), v("s","uomo (sostantivo)"), v("xw","proteggere (radice verbale)"), v("kA=f","il suo ka (ka + suff. 3ms)"), v("mAa-xrw","giusto di voce = defunto glorificato"), v("autobiografia tombale","genere letterario egiziano funerario")],
   "Lo studente legge un'autobiografia tombale semplice. Comprende ink come pronome indipendente enfatico. Usa mAa-xrw come titolo onorifico. Conosce il genere delle autobiografie tombali."),
  ("letteratura", "Il Racconto di Sinuhe (XII din.): 'iw=i Xr sAsA xAa tp=i' (stavo tremando, la testa mi cadeva)",
   "Lezione 16: il Racconto di Sinuhe — capolavoro della letteratura egiziana (XII dinastia). Si introduce il genere narrativo egiziano. Si analizza iw=i Xr sAsA (io stavo tremando — progressivo alla 1ª sing.). Contesto letterario: Sinuhe come esule che desidera tornare in Egitto.",
   [v("Sinuhe","protagonista del racconto — esule che torna"), v("XII Dinastia","periodo classico dell'egiziano medio (2000-1700 a.C.)"), v("iw=i Xr sAsA","io stavo tremando (progr. 1cs)"), v("Xr + inf.","forma progressiva con radici di movimento"), v("xAa","cadere, abbandonare"), v("genere narrativo","primo grande romanzo della storia")],
   "Lo studente legge frasi dal Racconto di Sinuhe. Comprende il progressivo alla 1ª persona. Conosce Sinuhe come capolavoro della letteratura mondiale. Apprezza il genere narrativo nell'antico Egitto."),
  ("revisione A1.1", "Revisione generale: alfabeto uniliterale, bilitterali, determinativi, pronomi, preposizioni, Htp di nsw, sDm=f, sDm.n=f",
   "Lezione 17 — conclusiva dell'Egiziano A1.1. Riepilogo dell'intero livello: sistema di scrittura (unilitterali, bilitterali, trilitterali, determinativi), morfologia (sostantivi, pronomi, preposizioni, verbi), testi (formula dell'offerta, Libro dei Morti, Racconto di Sinuhe). Proiezione verso l'A1.2.",
   [v("uniliterale","24 segni di un suono"), v("biliterale","segni di due suoni"), v("determinativo","segno muto semantico"), v("sDm=f","forma verbale base"), v("sDm.n=f","perfetto narrativo"), v("Htp di nsw","formula funeraria")],
   "Lo studente consolida le basi dell'egiziano geroglifico. Riconosce le forme fondamentali. Legge testi semplici con supporto. È pronto per l'A1.2 e i testi più complessi."),
]

EG_A11 = [L(d[1], d[2], d[3], d[4]) for d in EG_A11_DATA]

EG_A12 = [
  L("nTr nfr nb tAwy — Il Tempio egiziano e le sue iscrizioni. Si leggono iscrizioni dai templi di Karnak e Luxor.",
    "Lezione 1 dell'Egiziano A1.2: le iscrizioni templari. Si lavora su testi dai templi di Karnak, Luxor e Abu Simbel. La struttura del tempio come testo cosmologico. Le scene di offerta e le formule associative. Lessico del culto e del rituale.",
    [v("Karnak","complesso templare di Amon a Tebe"), v("nTr nfr","il dio buono (epiteto del faraone)"), v("nb tAwy","signore delle Due Terre"), v("kA","il doppio spirituale del faraone"), v("wAD wr","il grande verde = il mare")], "Lo studente legge iscrizioni templari di base. Comprende la struttura del tempio come cosmo. Usa il lessico del culto. Riconosce i titoli regali nei testi templari."),
  L("Testi delle Bare (XI-XII din.): apertura e lessico della resurrezione. anx-titi m Hrt-nTr (vivente sulla terra dei morti)",
    "Lezione 2: i Testi delle Bare come estensione democratizzata dei Testi delle Piramidi. Si lavora su anx-titi (vivente — participio attivo antico). L'accessibilità alla resurrezione oltre la classe reale. Lessico funerario avanzato.",
    [v("Testi delle Bare","corpus funerario XI-XII din."), v("anx-titi","vivente (forma verbale arcaica)"), v("Hrt-nTr","necropoli, regno dei morti"), v("democratizzazione","estensione della resurrezione a tutti i defunti"), v("participio antico","forma verbale arcaica con valore di participio")], "Lo studente legge frasi dai Testi delle Bare. Comprende il participio antico. Conosce la democratizzazione della resurrezione. Analizza il lessico della vita dopo la morte."),
  L("Racconto dell'Eloquente Contadino (Medio Regno): nDs pw Hr Dd mAat (è un plebeo che dice la verità)",
    "Lezione 3: il Racconto dell'Eloquente Contadino (Medio Regno). Si lavora su pw come copula (è). Si analizza Hr Dd come progressivo (che sta dicendo). Tema letterario: la giustizia e la voce dei deboli. Il genere del racconto didattico.",
    [v("nDs","plebeo, uomo comune"), v("pw","è (copula nominalizzante)"), v("Hr Dd","che sta dicendo (progressivo)"), v("mAat","verità, giustizia (Maat)"), v("racconto didattico","genere letterario con scopo morale")], "Lo studente usa pw come copula. Comprende il progressivo Hr + infinito. Legge un testo del Racconto dell'Eloquente Contadino. Riflette sul tema della giustizia nella letteratura egiziana."),
  L("Istruzione di Ptahhotep (V din.): sDm nA n rmT nfr pw (ascoltare è bene per gli uomini)",
    "Lezione 4: le Istruzioni sapienziali — Ptahhotep. Le istruzioni (sebayt) sono il genere sapienziale egiziano per eccellenza. Si lavora su sDm come infinito sostantivato (il sentire, l'ascoltare). Il genitivo indiretto n (nA n rmT = degli uomini).",
    [v("sebayt","istruzione, insegnamento (genere sapienziale)"), v("Ptahhotep","visir della V dinastia, saggio)"), v("infinito sostantivato","infinito come soggetto o oggetto"), v("nA n","il/la/i/le di (genitivo indiretto)"), v("rmT","uomini, esseri umani (pl. di rmT)")], "Lo studente comprende l'infinito sostantivato. Usa nA n come genitivo indiretto. Legge un testo delle Istruzioni di Ptahhotep. Conosce il genere delle istruzioni sapienziali egiziane."),
  L("Inno ad Aton (Akhenaton): nfr xrw=k nfr xt nbt ntk (bella è la tua voce, bella ogni cosa che sei tu)",
    "Lezione 5: l'Inno ad Aton di Akhenaton (XVIII dinastia). Il testo più vicino al monoteismo dell'antico Egitto. Si lavora su nfr xrw=k (bella è la tua voce — predicazione verbale). Il concetto di Aton come disco solare unico. Confronto con Salmo 104.",
    [v("Aton","il disco solare (dio di Akhenaton)"), v("Akhenaton","faraone 'eretico' XVIII din."), v("nfr xrw=k","bella è la tua voce (pred. verbale)"), v("xrw","voce, suono"), v("monoteismo solare","teologia di Aton: un solo dio creatore")], "Lo studente legge frasi dall'Inno ad Aton. Comprende la predicazione verbale. Conosce Akhenaton e la riforma religiosa. Analizza il parallelismo con Salmo 104."),
  L("Stele di Thutmosi III — testo militare: ix bw xr n rA=i (che cosa non cade dalla mia bocca)",
    "Lezione 6: le iscrizioni militari dei faraoni del Nuovo Regno. Si lavora su bw + negazione verbale come forma negativa non semplice. Si analizza la struttura dell'iscrizione militare: elenco di conquiste, epiteti eroici, formula della vittoria. Lessico militare egiziano.",
    [v("bw + neg.","negazione nominale"), v("rA","bocca; Ra (dio del sole)"), v("conquista (nxt)","vittoria, forza"), v("annali militari","genere documentario reale"), v("Thutmosi III","faraone guerriero XVIII din.")], "Lo studente comprende la negazione bw. Legge iscrizioni militari di base. Conosce Thutmosi III e le conquiste del Nuovo Regno. Analizza il genere degli annali militari."),
  L("Revisione A1.2 e testi funerari avanzati: Libro dei Morti cap. 1 — ingresso nell'aldilà",
    "Lezione 7: revisione dell'A1.2 e approfondimento del Libro dei Morti. Si ripassano le forme verbali principali (sDm=f, sDm.n=f, progressivo, iussivo). Si leggono frasi del capitolo 1 del Libro dei Morti (ingresso nell'aldilà). Preparazione all'A1.2 livello avanzato.",
    [v("Libro dei Morti cap. 1","ingresso dell'anima nell'aldilà"), v("r nw prt m hrw","il Libro dell'Uscire durante il Giorno"), v("revisione","sDm=f, sDm.n=f, progressivo, genitivo"), v("testo funerario","uso nell'aldilà o sulla stele")], "Lo studente consolida le forme verbali dell'A1.2. Legge frasi dal Libro dei Morti capitolo 1. Comprende il sistema delle forme verbali. È pronto per il livello A2."),
  L("Conclusione e riepilogo — Egiziano A1.2. Scrittura, grammatica, letteratura: un percorso nell'antico Egitto.",
    "Lezione 8 — conclusiva dell'Egiziano A1.2. Riepilogo dell'intero percorso A1: sistema di scrittura, morfologia di base, testi fondamentali (Testi delle Piramidi, Testi delle Bare, Libro dei Morti, letteratura del Medio Regno, inni del Nuovo Regno). Proiezione verso l'A2.",
    [v("sistema tripartito","fonogrammi + logogrammi + determinativi"), v("sDm=f","paradigma verbale base"), v("sDm.n=f","perfetto narrativo"), v("Medio Regno","periodo classico dell'egiziano letterario"), v("Nuovo Regno","periodo degli inni e dei testi di Amarna")], "Lo studente consolida tutto il percorso A1 dell'egiziano geroglifico. Riconosce le forme fondamentali. È in grado di leggere testi brevi con supporto. È pronto per l'A2 e testi più complessi."),
]

EG_A21 = [
  L("wn=f nfr — Ripasso sintattico avanzato. La proposizione verbale e nominale in egiziano medio.",
    "Lezione 1 dell'Egiziano A2: sintassi avanzata. Si ripassa la struttura della frase verbale (iw + sDm=f) e nominale (soggetto + predicato senza copula). Si introduce il genitivo diretto (stato costrutto) vs. genitivo indiretto (nA n). Esercizi su testi autentici.",
    [v("frase verbale","iw + sDm=f come struttura base"), v("frase nominale","sogg. + pred. senza copula"), v("genitivo diretto","stato costrutto senza preposizione"), v("genitivo indiretto","nA n + sostantivo"), v("particella iw","marcatore iniziale della frase verbale")], "Lo studente comprende le due strutture di frase fondamentali. Distingue genitivo diretto e indiretto. Legge testi autentici con struttura complessa. Analizza la sintassi egiziana."),
  L("Testo autentico: Papiro Westcar (XII-XVII din.) — i miracoli dei maghi. aq=f r pr pn (egli entrò in questa casa)",
    "Lezione 2: il Papiro Westcar — racconto di magia alla corte di Cheope. Si lavora su aq=f (egli entrò — sDm=f di aq = entrare). Il testo è uno dei più antichi esempi di narrativa fantastica. Il concetto di Heka (magia) nella cultura egiziana.",
    [v("Papiro Westcar","racconto di magia XVII-XII din."), v("aq=f","egli entrò (sDm=f di aq)"), v("Heka","magia (personificata come dio)"), v("pr","casa, palazzo"), v("narrativa fantastica","genere letterario egiziano")], "Lo studente legge frasi dal Papiro Westcar. Comprende sDm=f delle radici bilitere. Conosce il Papiro Westcar come racconto di magia. Analizza il genere della narrativa fantastica egiziana."),
  L("Iscrizione di Harkhuf (VI din.): ink sA n rmT (io sono figlio di uomini — autobiografia tombale)",
    "Lezione 3: le grandi autobiografie tombali del periodo classico. Si analizza l'autobiografia di Harkhuf, esploratore della Nubia. Si lavora su ink sA n rmT (io sono figlio di uomini — formula di vanto). Le virtù canoniche dell'autobiografia: mAat, nfr, onestà.",
    [v("Harkhuf","esploratore nubiano VI din."), v("ink sA n rmT","io sono figlio di uomini (formula)"), v("sA","figlio, difensore"), v("autobiografia tombale","lista di virtù e successi del defunto"), v("Nubia (Ta-Seti)","territorio a sud dell'Egitto")], "Lo studente legge un'autobiografia tombale avanzata. Comprende ink + predicato come frase nominale. Conosce Harkhuf e le esplorazioni nubiane. Analizza il genere autobiografico egiziano."),
  L("La Regina Hatshepsut — iscrizioni di Deir el-Bahari: Hmt-nTr tpy.t n Imn (la Prima Profetessa di Amon)",
    "Lezione 4: Hatshepsut e il potere femminile nell'Egitto antico. Si lavora sul titolo Hmt-nTr tpy.t (Prima Profetessa). Si analizza tpy.t come superlativo femminile (prima, principale). Contesto storico: Hatshepsut come faraone donna (XVIII dinastia).",
    [v("Hatshepsut","faraona XVIII dinastia"), v("Hmt-nTr","serva del dio, profetessa"), v("tpy.t","la prima (femm. di tpy)"), v("Imn","Amon (dio di Tebe)"), v("Deir el-Bahari","tempio funerario di Hatshepsut")], "Lo studente comprende tpy.t come superlativo. Legge titoli sacerdotali femminili. Conosce Hatshepsut e il suo regno. Analizza il potere femminile nell'Egitto antico."),
  L("Conclusione del corso di Egiziano Geroglifico. xr iw=n r smA tA (e noi andremo a unirci alla terra — la morte come 'unione con la terra')",
    "Lezione 5 — conclusiva dell'Egiziano A2. Riepilogo dell'intero percorso: scrittura geroglifica, sistema verbale (sDm=f, sDm.n=f, progressivo, iussivo, negazioni), generi letterari (autobiografie, istruzioni, racconti, inni, testi funerari). La formula di conclusione xr iw=n r smA tA.",
    [v("smA tA","unirsi alla terra (eufemismo per la morte)"), v("xr iw=n r","e noi andremo a (consecutivo)"), v("riepilogo","sDm=f, sDm.n=f, genitivo, pronomi, preposizioni"), v("lingua morta/viva","l'egiziano come codice culturale ancora leggibile")], "Lo studente consolida tutto il percorso A dell'egiziano geroglifico. È in grado di leggere testi autentici con dizionario. Comprende i principali generi letterari. Conosce le strutture sintattiche fondamentali dell'egiziano medio."),
]

IDS_EG_A11 = [
  "cmpf46dui00c7mjsd4tx0zs8i", "cmpf46dya00c9mjsdux4nf8nq", "cmpf46e1y00cbmjsdv7o9lf9f",
  "cmpf46e5m00cdmjsdu0aiye6v", "cmpf46e9e00cfmjsd7xalouc6", "cmpf46ed600chmjsd5nvgf2m4",
  "cmpf46egu00cjmjsdqy1vffrf", "cmpf46ekj00clmjsd74pnruef", "cmpf46eo200cnmjsd0rfk2qjm",
  "cmpf46erv00cpmjsdmw3webm6", "cmpf46evm00crmjsdykv2poif", "cmpf46eza00ctmjsdg8a16fsr",
  "cmpf46f2p00cvmjsd3jfnm8e0", "cmpf46f6f00cxmjsdbe03yis8", "cmpf46fa100czmjsdegt0kn7b",
  "cmpf46fdq00d1mjsd5mn0e5tq", "cmpf46fhe00d3mjsdu1vg4dx6", "cmpf46fl600d5mjsdsbal62lq",
]
IDS_EG_A12 = [
  "cmpf46fw200d7mjsd18s4qmj0", "cmpf46fzu00d9mjsd67xkt5ar", "cmpf46g3i00dbmjsd8xt5nyjw",
  "cmpf46g7200ddmjsdaxrjdyyo", "cmpf46gap00dfmjsd19u4u8o6", "cmpf46gei00dhmjsdpp8jvv93",
  "cmpf46gi200djmjsdtc3fx5gj", "cmpf46glv00dlmjsdkz46v3j6",
]
IDS_EG_A21 = [
  "cmpf46gwh00dnmjsdx8kirafr", "cmpf46h0800dpmjsdzdqzbsl4", "cmpf46h3y00drmjsd7cfbxrgt",
  "cmpf46h7m00dtmjsdfs234txx", "cmpf46hb900dvmjsd9ni3mbgv",
]

def run():
    conn = psycopg2.connect(DB_URL)
    cur = conn.cursor()
    total = 0
    for ids, data, label in [
        (IDS_EB_A11, EB_A11, "eb-a11"),
        (IDS_EB_A12, EB_A12, "eb-a12"),
        (IDS_EB_A21, EB_A21, "eb-a21"),
        (IDS_EG_A11, EG_A11, "eg-a11"),
        (IDS_EG_A12, EG_A12, "eg-a12"),
        (IDS_EG_A21, EG_A21, "eg-a21"),
    ]:
        assert len(ids) == len(data), f"{label}: {len(ids)} IDs vs {len(data)} records"
        for lid, lesson in zip(ids, data):
            cur.execute("""UPDATE "Lesson" SET "textFragment"=%s,"contentSummary"=%s,"keyVocabulary"=%s::jsonb,"learningObjectives"=%s WHERE id=%s""",
                (lesson["textFragment"], lesson["contentSummary"],
                 json.dumps(lesson["keyVocabulary"], ensure_ascii=False),
                 lesson["learningObjectives"], lid))
            total += 1
        print(f"  ✓ {label}: {len(data)} lezioni")
    conn.commit()
    conn.close()
    print(f"\nTotale: {total}")

if __name__ == "__main__":
    run()
