#!/usr/bin/env python3
"""seed-greek-b1.py — Greek B1.1, B1.2, B1.3 (authentic texts)"""

import psycopg2, json

DB_URL = "postgresql://neondb_owner:npg_wRBXT6Azv0Vj@ep-late-sea-aqyed9xw-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

def v(term, meaning, notes=None):
    d = {"term": term, "meaning": meaning}
    if notes: d["notes"] = notes
    return d
def L(tf, cs, kv, lo):
    return {"textFragment": tf, "contentSummary": cs, "keyVocabulary": kv, "learningObjectives": lo}

# ── B1.1 — 16 lezioni ─────────────────────────────────────────────────────────
GR_B11 = [
  L("Ἡρόδοτος Ἁλικαρνησσεὺς ἱστορίης ἀπόδεξιν ἥδε ποιέεται, ὡς μήτε τὰ γενόμενα ἐξ ἀνθρώπων τῷ χρόνῳ ἐξίτηλα γένηται, μήτε ἔργα μεγάλα τε καὶ θωμαστά, τὰ μὲν Ἕλλησι τὰ δὲ βαρβάροισι ἀποδεχθέντα, ἀκλεᾶ γένηται.",
   "Il proemio delle Storie di Erodoto (I,1): il primo testo storico-letterario in prosa greca. Si lavora sul dialetto ionico (ἱστορίης per ἱστορίας, -οισι per -οις). Si analizza la struttura sintattica con ὡς + congiuntivo aoristo (proposizione finale).",
   [v("ἀπόδεξις","esposizione, dimostrazione"), v("ποιέεται","compie, presenta (dial. ion. di ποιέομαι)"), v("ὡς + cong.","affinché (finale)"), v("ἐξίτηλα γένηται","svanisc(an)o, cadano nell'oblio"), v("θωμαστά","meravigliosi, mirabili (dial. ion.)"), v("βάρβαροι","non-Greci, barbari"), v("ἀκλεᾶ γένηται","diventino senza gloria"), v("τῷ χρόνῳ","col tempo (dat. causa)")],
   "Lo studente legge il proemio di Erodoto nell'originale ionico. Riconosce le principali differenze tra ionico e attico. Comprende ὡς + congiuntivo come proposizione finale. Analizza la struttura retorica del proemio."),
  L("Ἡρόδοτος, Ἱστορίαι Ι,5: 'Κροῖσος ἦν Λυδὸς μὲν γένος, παῖς δὲ Ἀλυάττεω, τύραννος δὲ ἐθνέων τῶν ἐντὸς Ἅλυος ποταμοῦ... Οὗτος ὁ Κροῖσος βαρβάρων πρῶτος τῶν ἡμεῖς ἴδμεν τοὺς μὲν κατεστρέψατο Ἑλλήνων, τοὺς δὲ φίλους προσεποιήσατο.'",
   "La presentazione di Creso (Erodoto I,5-6). Si lavora sul genitivo assoluto implicito con il participio (γένος = per stirpe). Si analizza ἴδμεν come forma di perfetto con senso di presente di οἶδα (noi sappiamo). Contesto storico: Creso e la Lidia.",
   [v("Λυδός","Lidio (di Lidia)"), v("γένος","per nascita, per stirpe (acc. di rispetto)"), v("ἐντός + gen.","dentro, al di qua di"), v("ἴδμεν","sappiamo (perf. pl. di οἶδα)"), v("κατεστρέψατο","sottomise (aor. med. di καταστρέφω)"), v("προσεποιήσατο","si procurò come amici (aor. med.)"), v("τῶν ἡμεῖς ἴδμεν","di quelli che conosciamo (rel.)")],
   "Lo studente legge un testo autentico di Erodoto. Comprende ἴδμεν come forma perfettiva di οἶδα. Analizza il genitivo assoluto in testi storiografici. Conosce il ruolo di Creso nella storia delle Guerre Persiane."),
  L("Θουκυδίδης, Ι,1: 'Θουκυδίδης Ἀθηναῖος ξυνέγραψε τὸν πόλεμον τῶν Πελοποννησίων καὶ Ἀθηναίων, ὡς ἐπολέμησαν πρὸς ἀλλήλους, ἀρξάμενος εὐθὺς καθισταμένου καὶ ἐλπίσας μέγαν τε ἔσεσθαι.'",
   "Il proemio delle Storie di Tucidide (I,1): il manifesto della storiografia scientifica. Si lavora sui participi aoristi in catena (ἀρξάμενος, ἐλπίσας) come participi congiunti. Si analizza ἐλπίσας ἔσεσθαι come accusativo + infinito futuro (sperandolo futuro).",
   [v("ξυνέγραψε","compose (aor. di ξυγγράφω, var. di συγγράφω)"), v("ὡς ἐπολέμησαν","come/quando combatterono"), v("πρὸς ἀλλήλους","l'uno contro l'altro"), v("ἀρξάμενος","avendo cominciato (aor. part. dep.)"), v("εὐθύς","subito, sin dall'inizio"), v("καθισταμένου","mentre si metteva in moto (gen. ass.)"), v("ἐλπίσας ἔσεσθαι","sperando che sarebbe stato (AcI fut.)")],
   "Lo studente analizza la catena di participi congiunti. Comprende ἐλπίζω + AcI futuro. Legge il proemio di Tucidide nell'originale. Confronta il metodo storiografico di Erodoto e Tucidide."),
  L("Θουκυδίδης, ΙΙ,35 (Epitafio di Pericle): 'Χρώμεθα γὰρ πολιτείᾳ οὐ ζηλούσῃ τοὺς τῶν πέλας νόμους, παράδειγμα δὲ μᾶλλον αὐτοὶ ὄντες τισίν.'",
   "L'Epitafio di Pericle in Tucidide (II,35-46): la lode della democrazia ateniese. Si lavora sul participio presente ζηλούσῃ (che emula, che imita) concordato con πολιτεία. Si analizza ὄντες come participio predicativo di αὐτοί. Testo fondamentale della letteratura politica greca.",
   [v("πολιτεία","costituzione, forma di governo"), v("ζηλούσῃ","che emula (dat. femm. part. pres. di ζηλόω)"), v("τοὺς τῶν πέλας νόμους","le leggi dei vicini"), v("παράδειγμα","modello, esempio"), v("μᾶλλον","piuttosto, di più"), v("ὄντες τισίν","essendo modello per qualcuno (part. pred.)")],
   "Lo studente analizza il participio predicativo concordato con il soggetto. Comprende παράδειγμα come predicato nominale ellittico. Legge l'Epitafio di Pericle nell'originale. Analizza la retorica della lode democratica."),
  L("Πλάτων, Ἀπολογία 17a: 'Ὅτι μὲν ὑμεῖς, ὦ ἄνδρες Ἀθηναῖοι, πεπόνθατε ὑπὸ τῶν ἐμῶν κατηγόρων, οὐκ οἶδα· ἐγὼ δ' οὖν καὶ αὐτὸς ὑπ' αὐτῶν ὀλίγου ἐδεήθην ἐπιλαθέσθαι ἐμαυτοῦ.'",
   "L'Apologia di Socrate (17a): il discorso inaugurale al tribunale. Si lavora su πεπόνθατε come perfetto indicativo (2ª pl.) con valore di stato risultante. Si analizza ὀλίγου δεῖν come espressione idiomatica (quasi, per poco). Contesto: il processo a Socrate nel 399 a.C.",
   [v("πεπόνθατε","avete subito, siete stati influenzati (perf. 2ª pl. di πάσχω)"), v("κατήγοροι","accusatori"), v("οὐκ οἶδα","non so (perf. di οἶδα)"), v("ὀλίγου ἐδεήθην","per poco mancò (quasi)"), v("ἐπιλαθέσθαι","dimenticare (aor. inf. di ἐπιλανθάνομαι)"), v("ἐμαυτοῦ","me stesso (pron. rifl. gen.)")],
   "Lo studente comprende il perfetto con valore di stato risultante. Usa ὀλίγου δεῖν come idioma. Legge l'inizio dell'Apologia di Socrate nell'originale. Analizza la strategia retorica del discorso d'apertura."),
  L("Πλάτων, Ἀπολογία 28e: 'Ὁ γὰρ τοῦ θανάτου δέος, ὦ ἄνδρες, δοκεῖν σοφὸν εἶναι μὴ ὄντα σκοπεῖτε.'",
   "Socrate sulla paura della morte (Apologia 28e). Si lavora sull'uso di δεῖν (sembrar di essere) e μὴ ὤν (pur non essendo). Si introduce il participio congiunto con μή (negazione del participio). Contesto filosofico: il coraggio di Socrate di fronte alla morte.",
   [v("δέος, -ους","paura, timore (III decl. neutro)"), v("δοκεῖν σοφὸν εἶναι","sembrare di essere saggio"), v("μὴ ὤν","pur non essendo (part. con μή)"), v("σκοπεῖτε","considerate! (imper. pl. di σκοπέω)"), v("τοῦ θανάτου","della morte (gen. di specificazione)")],
   "Lo studente comprende il participio negato con μή. Analizza l'infinitiva con δοκεῖν. Legge un passaggio chiave dell'Apologia. Riflette sul tema del coraggio e della saggezza in Socrate."),
  L("Πλάτων, Φαίδων 64a: 'Ὡς ἔοικεν... οἱ ὀρθῶς φιλοσοφοῦντες ἀποθνῄσκειν μελετῶσιν, καὶ τὸ τεθνάναι ἥκιστα αὐτοῖς ἀνθρώπων δεινόν.'",
   "Il Fedone: la filosofia come meditazione sulla morte. Si lavora su μελετάω + infinito (esercitarsi a fare). Si analizza τὸ τεθνάναι come infinito sostantivato (il morire). Contesto filosofico: il Fedone e l'ultima giornata di Socrate.",
   [v("ὡς ἔοικεν","come sembra, a quanto pare"), v("ὀρθῶς φιλοσοφοῦντες","coloro che filosofano rettamente (part.)"), v("μελετῶσιν + inf.","si esercitano a (μελετάω)"), v("τό τεθνάναι","il morire (inf. perf. sostant.)"), v("ἥκιστα","meno di tutti, per niente (superlat.)"), v("δεινόν","terribile, tremendo")],
   "Lo studente comprende μελετάω + infinito. Analizza l'infinito sostantivato con l'articolo (τό + inf.). Legge un testo fondamentale del Fedone. Comprende la visione platonica della filosofia come preparazione alla morte."),
  L("Ξενοφῶν, Ἀνάβασις Ι,2,7: 'Κῦρος ἐστρατεύετο ἔχων... Ἕλληνας στρατιώτας, λέγων ὡς ἐπὶ Πισίδας βούλοιτο στρατεύεσθαι.'",
   "L'inizio dell'Anabasi di Senofonte (I,2,7): Ciro e i mercenari greci. Si lavora su λέγων ὡς + ottativo (discorso indiretto con ottativo obliquo). Si introduce la distinzione tra il discorso indiretto con indicativo (Erodoto/Tucidide) e con ottativo (Senofonte).",
   [v("ἐστρατεύετο","marciava (imperf. dep. di στρατεύομαι)"), v("ἔχων","avendo con sé (part. pres. di ἔχω)"), v("λέγων ὡς + ott.","dicendo che (discorso ind. con ott.)"), v("βούλοιτο","volesse (ott. pres. di βούλομαι)"), v("Πισίδαι","Pisidi (popolo dell'Asia Minore)"), v("στρατεύεσθαι","fare una spedizione (inf. dep.)")],
   "Lo studente comprende il discorso indiretto con ottativo obliquo. Distingue ὡς + ottativo da ὅτι + indicativo nel discorso indiretto. Legge un testo dell'Anabasi di Senofonte. Conosce il contesto della spedizione dei Diecimila."),
  L("Ξενοφῶν, Ἀνάβασις ΙV,7,24: 'Καὶ πρῶτος Θήρων ἀνέβη, καὶ ἐπεὶ ἐπὶ τῇ κορυφῇ ἦν, ἐβόα· Θάλαττα, θάλαττα.'",
   "La scena del mare (Anabasi IV,7,24): i Diecimila vedono il Ponto. Si lavora sul valore del discorso diretto come momento culminante narrativo. Si analizza l'uso di πρῶτος come predicativo (fu il primo a salire). Testo tra i più celebri della prosa greca.",
   [v("πρῶτος","il primo (predicativo: fu il primo a)"), v("Θήρων","Terrone (soldato greco, nome)"), v("ἀνέβη","salì (aor. di ἀναβαίνω)"), v("κορυφή","cima, vetta"), v("ἐβόα","gridava (imperf. di βοάω)"), v("θάλαττα","il mare! (esclamazione)","uno dei più celebri momenti della narrativa greca")],
   "Lo studente comprende πρῶτος come predicativo. Analizza la funzione narrativa del discorso diretto. Legge uno dei testi più famosi della letteratura greca. Riflette sul pathos del momento narrativo."),
  L("Σοφοκλῆς, Οἰδίπους Τύραννος 1-5: 'Ὦ τέκνα, Κάδμου τοῦ πάλαι νέα τροφή, τίνας ποθ' ἕδρας τάσδε μοι θοάζετε ἱκετηρίοις κλάδοισιν ἐξεστεμμένοι;'",
   "L'apertura dell'Edipo Re di Sofocle (vv.1-5). Si lavora sul dialetto attico-ionico della tragedia e sulle peculiarità metriche del trimetro giambico. Si analizza ἐξεστεμμένοι come participio perfetto passivo concordato con il soggetto. Testo cardine della tragedia classica.",
   [v("τέκνα","figli, bambini (pl. di τέκνον)"), v("τοῦ πάλαι","dell'antico (art. + avv. sostant.)"), v("νέα τροφή","nuova generazione (lett. 'nutrimento')"), v("ποθ'","un tempo, mai (encl.)"), v("ἕδρας θοάζετε","sedete in questi posti (raro)"), v("ἱκετηρίοις κλάδοισιν","con rami supplici"), v("ἐξεστεμμένοι","incoronati (part. perf. pass.)")],
   "Lo studente legge i versi d'apertura dell'Edipo Re. Riconosce il trimetro giambico come metro tragico. Comprende il participio perfetto passivo in funzione aggettivale. Analizza l'impatto drammatico dell'incipit."),
  L("Σοφοκλῆς, Οἰδίπους Τύραννος 1186-1188: 'Ὦ γενεαὶ βροτῶν, / ὡς ὑμᾶς ἴσα καὶ τὸ μηδὲν / ζώσας ἐναριθμῶ.'",
   "Il terzo stasimo dell'Edipo Re (vv.1186-88): la meditazione sul nulla. Si lavora su τὸ μηδέν come infinito sostantivato (il niente). Si analizza ἴσα καί come equivalente di ὁμοίως καί (uguale a). Testo della nihilistica riflessione tragica sul destino umano.",
   [v("γενεαί","generazioni, stirpi (pl. di γενεά)"), v("βροτῶν","dei mortali (gen. pl. di βροτός)"), v("ὡς","come, quanto! (esclamativo)"), v("ἴσα καί","uguale a, tanto quanto"), v("τό μηδέν","il niente, il nulla (art. + pron. sost.)"), v("ζώσας","mentre vivete (part. pres. femm. pl.)"), v("ἐναριθμῶ","conto, annovero (ἐναριθμέω)")],
   "Lo studente comprende τό μηδέν come sostantivazione del pronome. Analizza ἴσα καί come correlazione di equivalenza. Legge un testo del terzo stasimo dell'Edipo Re. Riflette sul tema del destino nella tragedia greca."),
  L("Εὐριπίδης, Μήδεια 1-13 (πρόλογος): 'Εἴθε μήποτ' ἤλθομεν / εἰς γῆν Κόλχων Ἀργοῦς ναῦς ἡ κλεινὴ πλάτῃ.'",
   "Il prologo della Medea di Euripide (vv.1-13): la nutrice e il rimpianto. Si lavora su εἴθε + ottativo aoristo come ottativo desiderativo (potessimo non essere mai venuti). Si introduce il costrutto μήποτε come negazione del passato. Contesto letterario: Euripide e il dramma del personaggio.",
   [v("εἴθε + ott. aor.","oh se... ! (ottativo desiderativo del passato)"), v("μήποτ'","mai (con ottativo desiderativo)"), v("γῆ Κόλχων","terra dei Colchi (Caucaso)"), v("Ἀργώ","la nave Argo (mitologica)"), v("κλεινή","famosa, gloriosa"), v("πλάτῃ","con il remo (dat. strumentale)")],
   "Lo studente comprende εἴθε + ottativo aoristo come ottativo desiderativo del passato. Legge il prologo della Medea nell'originale. Analizza la funzione narrativa del prologo nella tragedia. Conosce il mito degli Argonauti."),
  L("Εὐριπίδης, Μήδεια 1019-1080 (μονόλογος): 'Τί δεῖ με πατέρα τῶν τούτων κακῶν / δὶς τοσάδε λυπεῖν, παῖδας ὀλέσαντ' ἐμούς;'",
   "Il grande monologo di Medea (vv.1019-80): la lotta interiore prima del delitto. Si lavora su τί δεῖ + accusativo + infinito (perché è necessario che io faccia). Si analizza il participio aoristo congiunto (ὀλέσαντ' = dopo aver perduto). Testo fondamentale della psicologia drammatica greca.",
   [v("τί δεῖ + acc. + inf.","perché è necessario che... (interrogativa retorica)"), v("δίς","due volte, doppiamente"), v("τοσάδε","tanto (agg./avv. di misura)"), v("λυπεῖν","addolorare (inf. di λυπέω)"), v("ὀλέσαντα","dopo aver perduto (aor. part. con acc. acc.)"), v("ἐμούς","miei (acc. pl. di ἐμός)")],
   "Lo studente comprende τί δεῖ + AcI come interrogativa retorica implicita. Analizza la catena di participi nel monologo. Legge il monologo più famoso di Euripide. Riflette sulla psicologia del personaggio tragico."),
  L("Ἀριστοτέλης, Ποιητική 1449b: 'ἔστιν οὖν τραγῳδία μίμησις πράξεως σπουδαίας καὶ τελείας... δι' ἐλέου καὶ φόβου περαίνουσα τὴν τῶν τοιούτων παθημάτων κάθαρσιν.'",
   "Aristotele, Poetica 1449b: la definizione di tragedia. Si lavora sul genitivo di specificazione (πράξεως = di un'azione). Si analizza il participio presente finale (περαίνουσα = compiendo, in modo da compiere). Testo fondamentale della teoria letteraria greca.",
   [v("μίμησις","imitazione, rappresentazione"), v("πρᾶξις, -εως","azione (III decl. femm.)"), v("σπουδαία","seria, di rilievo (femm. di σπουδαῖος)"), v("τελεία","completa, integra"), v("δι' ἐλέου καὶ φόβου","attraverso pietà e paura"), v("περαίνουσα","compiendo (part. pres. femm. di περαίνω)"), v("κάθαρσις, -εως","catarsi, purificazione"), v("παθήματα","le passioni, le emozioni (pl.)")],
   "Lo studente legge la definizione aristotelica di tragedia. Comprende il participio presente come proposizione relativa finale. Analizza il concetto di κάθαρσις. Applica la teoria al testo tragico."),
  L("Ἀριστοτέλης, Ἠθικά Νικομάχεια Ι,7: 'Εἰ δή τι τέλος ἐστὶ τῶν πρακτῶν ὃ δι' αὑτὸ βουλόμεθα, τοῦτο τἀγαθὸν εἶναι φαμέν, καὶ τὸ ἄριστον.'",
   "Aristotele, Etica Nicomachea I,7: la ricerca del sommo bene. Si lavora su εἰ + indicativo nella proposizione ipotetica logica (if there is indeed a final end). Si analizza τἀγαθόν come crasi di τό ἀγαθόν. Contesto filosofico: l'eudaimonia come fine supremo della vita etica.",
   [v("τέλος, -ους","fine, scopo (III decl. neutro)"), v("τῶν πρακτῶν","delle cose pratiche (gen. pl. di πρακτός)"), v("δι' αὑτό","per se stesso (pron. rifl.)"), v("τἀγαθόν","il bene (crasi di τό ἀγαθόν)"), v("φαμέν","diciamo (1ª pl. di φημί)"), v("ἄριστον","il migliore, il sommo bene (superlativo)")],
   "Lo studente comprende ε+ indicativo nella protasi logica. Analizza la crasi τἀγαθόν. Legge un testo dell'Etica Nicomachea. Comprende la ricerca aristotelica del τέλος e dell'εὐδαιμονία."),
  L("Revisione B1.1. Testi letti: Erodoto (ionico), Tucidide (attico), Platone (Apologia, Fedone), Senofonte (Anabasi), Sofocle (Edipo Re), Euripide (Medea), Aristotele (Poetica, Etica). Preparazione al B1.2: la lirica, gli storici del IV secolo, il Nuovo Testamento.",
   "Lezione conclusiva del B1.1: bilancio degli autori e delle strutture grammaticali avanzate affrontate. Si consolida: ottativo obliquo, participio congiunto, genitivo assoluto, AcI, ottativo desiderativo. Proiezione verso il B1.2.",
   [v("ὀπτατιβός","ottativo (modo verbale)"), v("γενική ἀπόλυτος","genitivo assoluto"), v("κατηγορηματικόν μετοχή","participio predicativo"), v("συζευγμένη μετοχή","participio congiunto"), v("ἀπαρέμφατος","infinito (modo verbale)")],
   "Lo studente consolida le strutture grammaticali avanzate del B1.1. Riconosce gli stili dei diversi autori greci classici. È in grado di leggere testi autentici con apparato critico. È pronto per il B1.2."),
]

GR_B12 = [
  L("Ἡρόδοτος, VII,228: 'Ὦ ξεῖν', ἄγγειλον Λακεδαιμονίοις ὅτι τῇδε κείμεθα τοῖς κείνων ῥήμασι πειθόμενοι.' Τοῦτο τὸ ἐπίγραμμα Σιμωνίδης ἐποίησεν.",
   "L'epitaffio delle Termopili (Erodoto VII,228 / Simonide, epigr.): il testo più breve e più famoso della letteratura greca. Si lavora su ξεῖν' (vocativo poetico di ξένος) e ὅτι + indicativo presente (messaggio indiretto). Contesto storico: la battaglia delle Termopili (480 a.C.).",
   [v("ξεῖνος (poet.)","straniero (= attico ξένος)"), v("ἄγγειλον","annuncia! (aor. imper. di ἀγγέλλω)"), v("τῇδε","qui, in questo luogo"), v("κείμεθα","giacciamo, siamo sepolti (κεῖμαι 1ª pl.)"), v("κείνων ῥήμασι","per gli ordini di costoro"), v("πειθόμενοι","obbedendo (part. pres.)"), v("Σιμωνίδης","Simonide di Ceo (poeta lirico)")],
   "Lo studente legge l'epitaffio delle Termopili nell'originale. Riconosce le forme poetiche (ξεῖνος). Comprende ὅτι + indicativo nel discorso indiretto. Analizza la struttura e il pathos dell'epigramma."),
  L("Θουκυδίδης, III,82: 'Καὶ ἡ εἰωθυῖα ἀξίωσις τῶν ὀνομάτων ἐς τὰ ἔργα ἀντηλλάγη τῇ δικαιώσει.'",
   "La patologia della guerra civile in Tucidide (III,82): il rovesciamento del significato delle parole. Si lavora su ἀντηλλάγη come aoristo passivo irregolare (fu scambiato). Si analizza l'espressione εἰωθυῖα ἀξίωσις (il consueto significato). Testo fondamentale della scienza politica.",
   [v("εἰωθυῖα","consueta, abituale (part. perf. di εἴωθα)"), v("ἀξίωσις, -εως","significato, valutazione"), v("ἐς τά ἔργα","in relazione ai fatti"), v("ἀντηλλάγη","fu scambiata (aor. pass. di ἀντ-αλλάσσω)"), v("δικαίωσις, -εως","pretesto, giustificazione")],
   "Lo studente comprende l'aoristo passivo irregolare. Analizza il costrutto τῶν ὀνομάτων ἀξίωσις. Legge il passo fondamentale sulla guerra civile in Tucidide. Riflette sul rapporto tra linguaggio e potere politico."),
  L("Πλάτων, Πολιτεία 514a (Μῦθος τοῦ Σπηλαίου): 'Ἄνθρωποι ἐν καταγείῳ οἰκήσει δεσμώτας ἔχε τετραμμένους πρὸς τὸ φῶς.'",
   "L'allegoria della caverna (Repubblica VII, 514a). Si lavora su ἔχε + participio (tienili vòlti = costruzione con εἶναι implicito). Si analizza il participio perfetto passivo τετραμμένους (rivolti, vòlti). Testo fondamentale dell'epistemologia platonica.",
   [v("κατάγειος/ον","sotterraneo, ipogeo"), v("οἴκησις, -εως","dimora, abitazione"), v("δεσμώτης, -ου","prigioniero, incatenato"), v("ἔχε + part.","tienili... (costruzione perifrast.)"), v("τετραμμένους","rivolti, vòlti (perf. part. pass. di τρέπω)"), v("πρὸς τό φῶς","verso la luce")],
   "Lo studente comprende εἶναι + participio come predicazione perifrastica. Analizza il participio perfetto passivo come attributo. Legge il testo fondamentale dell'allegoria della caverna. Comprende la teoria platonica della conoscenza."),
  L("Δημοσθένης, Α' Φιλιππικός, 2: 'Εἰ μέν, ὦ ἄνδρες Ἀθηναῖοι, περὶ καινοῦ τινος πράγματος προυτίθει λέγειν, ἐπισχὼν ἂν ἕως οἱ πλεῖστοι τῶν εἰωθότων εἰπεῖν εἰρήκεσαν, εἰ μὲν ἤρεσκέ μοι τὰ ῥηθέντα, ἡσύχαζον.'",
   "La Prima Filippica di Demostene (§2): periodo ipotetico misto complesso. Si lavora sul periodo ipotetico misto (protasi dell'irrealtà con εἰ + imperfetto; apodosi con ἄν + imperfetto). Si analizza la costruzione ἐπισχὼν ἕως (avendo aspettato fino a quando). Testo dell'oratoria politica attica.",
   [v("καινόν","nuovo, inedito"), v("προυτίθει","era proposto (impf. pass. irr. di προτίθημι)"), v("ἐπισχών","avendo aspettato (aor. part. di ἐπέχω)"), v("ἕως + ind.","fino a quando (temporale)"), v("εἰρήκεσαν","avevano detto (piuccheperfetto)"), v("ἤρεσκέ μοι","mi piaceva (imperf. di ἀρέσκω + dat.)"), v("ἡσύχαζον","tacevo (imperf. di ἡσυχάζω)")],
   "Lo studente analizza un periodo ipotetico misto dell'irrealtà. Comprende il piuccheperfetto come anteriorità al passato. Legge un testo dell'oratoria politica di Demostene. Analizza la strategia retorica dell'esordio."),
  L("Πίνδαρος, Ὀλυμπιόνικος Α', 1-7: 'Ἄριστον μὲν ὕδωρ, ὁ δὲ χρυσὸς αἰθόμενον πῦρ / ἅτε διαπρέπει νυκτὶ μεγάνορος ἔξοχα πλούτου.'",
   "Pindaro, Prima Olimpica 1-7: l'apertura della lirica corale. Si lavora sulla struttura tripartita (ἄριστον μέν / ὁ δέ / ...) e sulle metafore concentriche. Si analizza αἰθόμενον come participio medio in senso intransitivo (che arde, fiammeggiante). Contesto: la lirica corale come genere",
   [v("ἄριστον","la migliore, ottima (superlativo femm.)"), v("αἰθόμενον","che arde (part. med. di αἴθω)"), v("ἅτε","come, così come (particella comparativa)"), v("διαπρέπει","eccelle, risplende (διαπρέπω)"), v("νυκτί","di notte (dat. tempo)"), v("μεγάνωρ, -ορος","nobile, signorile (comp.)"), v("ἔξοχα + gen.","al di sopra di, più di (avv.)")],
   "Lo studente comprende la struttura tripartita μέν/δέ nell'apertura pindarica. Analizza il participio medio intransitivo. Legge i versi d'apertura della Prima Olimpica. Comprende la funzione celebrativa della lirica corale."),
  L("Σαπφώ, fr. 16 (Lobel-Page): 'Οἰ μὲν ἰππήων στρότον, οἰ δὲ πέσδων, / οἰ δὲ νάων φαῖσ' ἐπὶ γᾶν μέλαιναν / ἔμμεναι κάλλιστον, ἐγὼ δὲ κῆν' ὄτ-/τω τις ἔραται.'",
   "Saffo, fr. 16: il relativismo del desiderio. Si lavora sul dialetto eolico (ἰππήων per ἱππέων, οἰ per οἱ, γᾶν per γῆν). Si analizza la struttura trimembre (οἰ μέν / οἰ δέ / οἰ δέ) e la svolta personale (ἐγὼ δέ). Testo emblematico della soggettività lirica.",
   [v("ἰππήων στρότον","l'esercito di cavalleria (eolico)"), v("πέσδων","di fanti (gen. pl. eolico di πεζός)"), v("νάων","di navi (gen. pl. eolico)"), v("φαῖσ'","dicono (3ª pl. eolico di φημί)"), v("ἔμμεναι κάλλιστον","essere la cosa più bella"), v("κῆν' ὄττω","quello che (eolico per ἐκεῖνο ὅτι)"), v("ἔραται","desidera (eolico, dep.)")],
   "Lo studente riconosce le caratteristiche del dialetto eolico. Analizza la struttura contrastiva μέν/δέ moltiplicata. Legge il fr. 16 di Saffo nell'originale. Comprende il tema del desiderio e del relativismo estetico nella lirica greca."),
  L("Ἀλκαῖος, fr. 208 (Lobel-Page): 'Ἄσυνετον τό κάλλος οὐ τεθέαμαι / παρθένων γλαύκαν ἐχόντων χάριν / ἐν δέ μοι θύμῳ γλύκεια φαίνεται.'",
   "Alceo, fr. 208: la bellezza e il desiderio. Si lavora su τεθέαμαι come perfetto di θεάομαι (ho contemplato). Si analizza ἐν θύμῳ come locuzione avverbiale (nel cuore, nell'anima). Contesto: Alceo e la lirica eolica maschile.",
   [v("ἄσυνετον","incomprensibile (ἄ- privativo)"), v("τεθέαμαι","ho contemplato (perf. dep. di θεάομαι)"), v("παρθένων","delle fanciulle (gen. pl.)"), v("γλαύκαν χάριν","la grazia splendente (eolico)"), v("θύμος","animo, cuore (poetico)"), v("γλύκεια","dolce (femm. di γλυκύς)")],
   "Lo studente comprende il perfetto dei verbi deponenti. Analizza ἐν θύμῳ come locuzione avverbiale della lirica. Legge un frammento di Alceo. Conosce la lirica eolica maschile."),
  L("Ἀνακρέων, fr. 413: 'Σφαίρῃ δηὖτέ με πορφυρέῃ / βάλλων χρυσοκόμης Ἔρως / νήνῳ ποικιλοσαμβάλῳ / συμπαίζειν προκαλεῖται.'",
   "Anacreonte, fr. 413: Eros che gioca a palla. Si lavora sulla struttura participiale + verbo principale (βάλλων... προκαλεῖται). Si analizza il dativo strumentale (σφαίρῃ = con la palla). Contesto: la lirica simposiale ionica e la figura di Eros giocoso.",
   [v("σφαῖρα","palla (I decl.)"), v("δηὖτε","di nuovo (avv. poetico)"), v("πορφυρέη","purpurea (femm. ion.)"), v("βάλλων","lanciando (part. pres. di βάλλω)"), v("χρυσοκόμης Ἔρως","Eros dalla chioma d'oro (epiteto)"), v("νήνῳ","alla fanciulla"), v("προκαλεῖται","invita, sfida (dep. διά)")],
   "Lo studente analizza la struttura participio + verbo principale. Comprende il dativo strumentale. Legge un frammento di Anacreonte. Conosce la lirica simposiale ionica."),
  L("Θέογνις, 183-192: 'Πλεῖστον ἔχεις πλοῦτον χρυσόν τ' ἔλαβες πολὺν ἄλλων, / καὶ ψυχὴν ἔχεις πᾶσι χαριζομένην / πλούτου δ' εὐδοξίη τε καὶ ἀνδρῶν πολλῶν ἑτάρων / ψυχὴν τερπομένην.'",
   "Teognide, 183-192: ricchezza e virtù nella lirica gnomica. Si lavora su χαριζομένην come participio medio attributivo (anima che si dona a tutti). Si introduce la poesia gnomica come genere della sapienza arcaica. Contesto: il simposio e la trasmissione della saggezza.",
   [v("πλεῖστον","moltissimo (superlativo di πολύς)"), v("εὐδοξία","buona reputazione, gloria"), v("ἑτάρων","dei compagni (gen. pl. di ἑταῖρος)"), v("χαριζομένην","che si dona (part. med. di χαρίζομαι)"), v("τερπομένην","che si delizia (part. med. di τέρπομαι)")],
   "Lo studente comprende il participio medio attributivo. Conosce Teognide e la poesia gnomica. Legge un testo sulla ricchezza e la virtù. Comprende la funzione educativa del simposio greco."),
  L("Παῦλος, Πρὸς Κορινθίους Α' 13,1-3: 'Ἐὰν ταῖς γλώσσαις τῶν ἀνθρώπων λαλῶ καὶ τῶν ἀγγέλων, ἀγάπην δὲ μὴ ἔχω, γέγονα χαλκὸς ἠχῶν ἢ κύμβαλον ἀλαλάζον.'",
   "San Paolo, Prima Lettera ai Corinzi 13,1-3: l'inno alla carità. Si lavora su ἐάν + congiuntivo come protasi ipotetica eventualis (nel caso in cui io parli). Si analizza γέγονα come perfetto con valore di stato (sono diventato = sono). Testo della koiné ellenistica.",
   [v("ἐάν + cong.","se (protasi eventuale)"), v("γλώσσαις","lingue (dat. pl. di γλῶσσα)"), v("λαλῶ","parlo (λαλέω, cong. pres.)"), v("ἀγάπη","amore (agape)"), v("γέγονα","sono diventato (perf. di γίγνομαι)"), v("χαλκός","bronzo, rame"), v("ἠχῶν","risonante (part. pres. di ἠχέω)"), v("κύμβαλον","cembalo, piatto musicale"), v("ἀλαλάζον","che squilla (part. pres.)")],
   "Lo studente comprende ἐάν + congiuntivo come protasi eventuale. Analizza il perfetto γέγονα con valore di stato. Legge 1Cor 13 nella koiné originale. Conosce il registro della koiné ellenistica rispetto all'attico classico."),
  L("Πλούταρχος, Ἀλέξανδρος 14: 'Εἶπε δέ ποτε ἀκούσας ὅτι Φίλιππος πολλὰς πόλεις λαμβάνει· οὐ χαίρω, ὦ παῖδες, ὅτι ὁ πατήρ μου πολλὰ κατακτᾶται — φθάσει γὰρ πάντα μοι μετὰ τοῦ πατρὸς καταλαβών.'",
   "Plutarco, Vita di Alessandro 14: la paura di Alessandro che il padre conquisti tutto. Si lavora su φθάσει + participio aoristo come costruzione idiomatica (sarà stato il primo a prendere tutto). Si analizza l'uso del futuro semplice nella profezia del giovane Alessandro.",
   [v("εἶπε ποτε ἀκούσας","una volta, avendo sentito, disse"), v("Φίλιππος","Filippo II di Macedonia"), v("οὐ χαίρω","non gioisco"), v("κατακτᾶται","conquista (dep. κατακτάομαι)"), v("φθάσει + part.","sarà stato il primo a (φθάνω + part.)"), v("καταλαβών","avendo preso, conquistato")],
   "Lo studente comprende φθάνω + participio aoristo. Legge un aneddoto da Plutarco su Alessandro. Analizza la strategia narrativa del racconto biografico. Comprende il genere biografico nella letteratura tardo-classica."),
  L("Τέλος B1.2. Ἀνεγνώκαμεν λυρικούς, ἱστορικούς, φιλοσόφους, ὀρατόρας καὶ κείμενα τῆς κοινῆς. Ἐν τῷ B1.3 ἀναγνωσόμεθα τοὺς τραγικοὺς ἐπὶ πλέον καὶ τοὺς φιλοσόφους τοῦ Σωκράτους.",
   "Lezione conclusiva B1.2: bilancio dei generi letterari affrontati (lirica corale e monodica, storiografia, filosofia, oratoria, koiné). Revisione delle strutture grammaticali avanzate. Preparazione al B1.3.",
   [v("ἀνεγνώκαμεν","abbiamo letto (1ª pl. perf. di ἀναγιγνώσκω)"), v("λυρικοί","i lirici"), v("ὀρατόρες","gli oratori"), v("κοινή","lingua comune, koiné"), v("ἀναγνωσόμεθα","leggeremo (1ª pl. fut. di ἀναγιγνώσκω)")],
   "Lo studente consolida la lettura di testi in diversi dialetti e registri. Riconosce le caratteristiche stilistiche dei principali autori greci. È pronto per il B1.3 e la lettura autonoma."),
]

GR_B13 = [
  L("Εὐριπίδης, Ἑκάβη 1-20: 'Ἥκω νεκρῶν κευθμῶνα καὶ σκότου πύλας / λιπών, ἵν' οἰκεῖ χωρὶς οἱ θεοὶ βροτῶν.'",
   "L'Ecuba di Euripide: il prologo dello spettro di Polidoro. Si lavora su ἥκω come perfetto di senso presente (sono venuto = eccomi qui). Si analizza ἵνα + indicativo in senso relativo (dove, nel luogo in cui). Contesto letterario: il teatro euripideo del secondo periodo.",
   [v("ἥκω","sono venuto (perf. di senso pres.)"), v("νεκρῶν κευθμών","il nascondiglio dei morti (Ade)"), v("σκότου πύλαι","le porte del buio"), v("λιπών","avendo lasciato (aor. part. di λείπω)"), v("ἵνα + indic.","dove (relativo di luogo)"), v("χωρίς","separatamente, lontano da"), v("βροτοί","i mortali")],
   "Lo studente comprende ἥκω come perfetto di senso presente. Usa ἵνα come pronome relativo di luogo. Legge il prologo dell'Ecuba. Comprende la funzione dello spettro come personaggio prologante."),
  L("Αἰσχύλος, Ἀγαμέμνων 1-21 (φύλαξ): 'Θεοὺς μὲν αἰτῶ τῶνδ' ἀπαλλαγὴν πόνων, / φρουρᾶς ἐτείας μῆκος.'",
   "L'Agamennone di Eschilo: il prologo della sentinella. Si lavora su αἰτῶ + gen. + acc. (chiedo agli dèi la liberazione). Si analizza la metafora del cane come sentinella. Contesto letterario: l'Orestea come unica trilogia completa della tragedia greca.",
   [v("αἰτῶ + gen. + acc.","chiedo a (qualcuno) (qualcosa)"), v("ἀπαλλαγή + gen.","liberazione da"), v("πόνος","fatica, dolore"), v("φρουρά","guardia, sentinella"), v("ἐτεία","annuale, di un anno"), v("μῆκος, -ους","lunghezza, durata")],
   "Lo studente comprende αἰτέω con doppio caso. Analizza il valore della metafora nella tragedia. Legge il prologo dell'Agamennone. Conosce la struttura dell'Orestea come trilogia."),
  L("Αἰσχύλος, Ἀγαμέμνων 160-183 (χορός, ὕμνος Διός): 'Ζεύς, ὅστις ποτ' ἐστίν, εἰ τόδε / φίλον κεκλημένῳ, / τοῦτό νιν προσεννέπω.'",
   "L'Inno a Zeus nell'Agamennone (vv.160-183). Si lavora su ὅστις + ottativo come proposizione relativa indiretta (chiunque egli sia). Si analizza κεκλημένῳ come participio perfetto passivo (chiamato così). Testo fondamentale della teologia eschilea.",
   [v("ὅστις + ott.","chiunque sia (rel. generalizzante)"), v("φίλον","gradito, caro"), v("κεκλημένῳ","chiamato così (part. perf. pass. di καλέω)"), v("νιν","lui, lo (pron. enclitico poetico)"), v("προσεννέπω","rivolgo la parola, invoco (composto)")],
   "Lo studente comprende ὅστις + ottativo come relativo generalizzante. Analizza il participio perfetto passivo. Legge l'Inno a Zeus dell'Agamennone. Comprende la teologia eschilea della sofferenza come apprendimento."),
  L("Σοφοκλῆς, Φιλοκτήτης 1-14: 'Ἀκτὴ μὲν ἥδε τῆς θαλασσόπληκτος Λήμνου / ἄβατος ἀνθρώποις.'",
   "Il Filottete di Sofocle: il prologo su Lemno. Si lavora su θαλασσόπληκτος come aggettivo composto (battuta dal mare). Si analizza ἄβατος come aggettivo verbale con senso passivo (non percorsa = inaccessibile). Contesto letterario: la trilogia dei finali tardivi di Sofocle.",
   [v("ἀκτή","scoglio, costa, promontorio"), v("Λῆμνος","Lemno (isola greca)"), v("θαλασσόπληκτος","battuta dal mare (composto)"), v("ἄβατος/ον","inaccessibile, non calpestata (ἀ- + βαίνω)")],
   "Lo studente riconosce gli aggettivi verbali in -τος. Analizza composti aggettivali tipici del lessico poetico. Legge il prologo del Filottete. Conosce il tema dell'isolamento e della socialità nel Filottete."),
  L("Ἀριστοφάνης, Βάτραχοι 1-15: 'Εἴπω τι τῶν εἰωθότων, ὦ δέσποτα, / ἐφ' οἷς γελῶσ' ἀεὶ οἱ θεαταί;'",
   "Le Rane di Aristofane: il prologo di Xantia. Si lavora su εἴπω come congiuntivo deliberativo (devo dire?). Si analizza ἐφ' οἷς come locuzione preposizionale relativa (per le quali cose). Contesto letterario: la commedia aristofanea e il suo rapporto con il pubblico.",
   [v("εἴπω;","devo dire? (cong. deliberativo)"), v("τῶν εἰωθότων","delle cose consuete (part. perf. sostant.)"), v("ὦ δέσποτα","o padrone! (voc.)"), v("ἐφ' οἷς","per le quali cose, davanti alle quali"), v("γελῶσι","ridono (γελάω, 3ª pl. contr.)"), v("θεαταί","spettatori")],
   "Lo studente comprende il congiuntivo deliberativo. Analizza ἐπί + dativo relativo. Legge il prologo comico delle Rane. Comprende il rapporto diretto tra commedia aristofanea e pubblico."),
  L("Ἀριστοφάνης, Βάτραχοι 1008-1012: Εὐριπίδης λέγει· 'Ἀλλ' ἐγὼ μὲν εἰς μέσους / κατῆγον αὐτοὺς εἰς ἀγῶνας.' Αἰσχύλος δέ· 'Ἐγὼ δ' ἐτίθην παρεσκεύαζόν τ' εἰς τοὺς πολεμίους.'",
   "L'agone poetico tra Eschilo ed Euripide nelle Rane (vv.1008-1012). Si lavora sul contrasto tra i due stili. Si analizza κατῆγον εἰς ἀγῶνας (portai nelle gare/nella vita pubblica) come metafora del ruolo civico della tragedia. La commedia come critica letteraria.",
   [v("κατῆγον","portai giù, introdussi (imperf. di κατάγω)"), v("εἰς μέσους","in mezzo (lett. tra i/verso i medi)"), v("ἀγών, -ῶνος","gara, arena pubblica"), v("ἐτίθην","ponevo, componevo (imperf. di τίθημι)"), v("παρεσκεύαζον","preparavo (imperf. di παρασκευάζω)"), v("πολέμιοι","nemici")],
   "Lo studente analizza l'agone poetico come struttura drammatica. Comprende il valore civico della tragedia nella commedia aristofanea. Legge un testo dell'agone nelle Rane. Riflette sul ruolo politico della poesia greca."),
  L("Πλάτων, Κρίτων 50a-b: 'Ὦ Σώκρατες, ἡμεῖς σε ἐγεννήσαμεν, ἐθρέψαμεν, ἐπαιδεύσαμεν... σοί, ᾧ τῶν ἡμετέρων μετεδίδομεν ὧν οἷοί τ' ἦμεν.'",
   "Il Critone: le Leggi parlano a Socrate. Si lavora su μετεδίδομεν + genitivo (davamo parte di, condividevamo). Si analizza οἷοί τ' ἦμεν come espressione idiomatica (eravamo capaci di). Contesto filosofico: l'obbligo di obbedire alle leggi.",
   [v("ἐγεννήσαμεν","generammo (aor. di γεννάω)"), v("ἐθρέψαμεν","nutrimmo, allenammo (aor. di τρέφω)"), v("ἐπαιδεύσαμεν","educammo (aor. di παιδεύω)"), v("μετεδίδομεν + gen.","davamo parte di (μεταδίδωμι)"), v("οἷοί τ' ἦμεν","eravamo capaci (idiom. con τε)")],
   "Lo studente comprende μεταδίδωμι + genitivo. Analizza l'idioma οἷός τε εἰμί. Legge il discorso delle Leggi nel Critone. Riflette sul tema del contratto sociale in Platone."),
  L("Ἀριστοτέλης, Μετ. Α, 980a: 'Πάντες ἄνθρωποι τοῦ εἰδέναι ὀρέγονται φύσει. Σημεῖον δ' ἡ τῶν αἰσθήσεων ἀγάπησις.'",
   "L'incipit della Metafisica di Aristotele (980a1): la curiosità naturale dell'uomo. Si lavora su τοῦ εἰδέναι come genitivo dell'infinito (della conoscenza = di sapere). Si analizza ὀρέγονται come verbo deponente con genitivo (tendere a, desiderare). Testo fondamentale della filosofia occidentale.",
   [v("πάντες ἄνθρωποι","tutti gli uomini"), v("τοῦ εἰδέναι","di sapere (gen. dell'inf. = della conoscenza)"), v("ὀρέγονται + gen.","tendono a, desiderano (dep.)"), v("φύσει","per natura (dat. avv.)"), v("σημεῖον","indizio, segno"), v("αἴσθησις, -εως","percezione, sensazione"), v("ἀγάπησις","amore, affetto")],
   "Lo studente comprende il genitivo dell'infinito (τοῦ + inf.). Analizza ὀρέγομαι + genitivo. Legge l'incipit della Metafisica di Aristotele. Riflette sul desiderio naturale di sapere come fondamento della filosofia."),
  L("Θουκυδίδης, ΙΙ,65: 'Περικλῆς μὲν τοιαῦτα λέγων ἐπειρᾶτο τοὺς Ἀθηναίους τῆς τε ἐς ἐκεῖνον ὀργῆς παραλύειν καὶ ἀπὸ τῶν παρόντων δεινῶν ἀπάγειν τὴν γνώμην.'",
   "Il ritratto di Pericle in Tucidide (II,65): l'analisi del leader. Si lavora su ἐπειράτο + infinito come tentativo con imperfetto (stava cercando di). Si analizza τοιαῦτα λέγων come participio modale (dicendo tali cose = con queste parole). Contesto: il ritratto storico in Tucidide.",
   [v("τοιαῦτα","tali cose, queste cose (acc. pl. di τοιοῦτος)"), v("ἐπειρᾶτο + inf.","cercava di (imperf. dep. di πειράομαι)"), v("ὀργή + gen.","ira contro (ὀργή + εἰς = verso)"), v("παραλύειν","allentare, distogliere da (παραλύω)"), v("ἀπό + gen.","lontano da"), v("παρόντα δεινά","le presenti difficoltà (part. sostant.)"), v("γνώμη","pensiero, intenzione")],
   "Lo studente comprende πειράομαι + infinito con imperfetto come tentativo non riuscito. Analizza il participio modale. Legge il ritratto tucidideo di Pericle. Comprende la tecnica del ritratto storico."),
  L("Ξενοφῶν, Ἀπομνημονεύματα Ι,1,11: 'Οὐ γὰρ ὅπως κρύπτοι ἃ ἔπραττεν ἀλλ' ὅπως φανερώτατος εἴη πᾶσιν ἐπεμέλετο.'",
   "Senofonte, Memorabili I,1,11: Socrate non cerca la nascondimento. Si lavora su ὅπως + ottativo (come fare in modo che) come proposizione finale indiretta. Si analizza il contrasto ὅπως κρύπτοι / ὅπως φανερώτατος εἴη. Contesto: la difesa del carattere di Socrate.",
   [v("ὅπως + ott.","come fare in modo che (fin. indir.)"), v("κρύπτοι","nascondesse (ott. pres. di κρύπτω)"), v("ἃ ἔπραττεν","ciò che faceva (rel.)"), v("φανερώτατος","il più visibile (superlat. di φανερός)"), v("εἴη","fosse (ott. pres. di εἰμί)"), v("ἐπεμέλετο","si preoccupava (imperf. dep. di ἐπιμελέομαι)")],
   "Lo studente comprende ὅπως + ottativo come finale indiretta. Analizza il contrasto tra opposti come strategia retorica. Legge un testo dei Memorabili di Senofonte. Comprende la difesa del metodo socratico."),
  L("Λυσίας, Ὑπὲρ Μαντιθέου 1: 'Εἰ μὴ συνῄδη, ὦ βουλή, τοῖς κατηγόροις βουλομένοις ἐκ παντὸς τρόπου κακῶς ποιεῖν ἐμέ, πολλὴν ἂν αὐτοῖς χάριν εἶχον ταύτης τῆς κατηγορίας.'",
   "Lisia, Pro Mantiteo: l'esordio dell'apologia. Si lavora sul periodo ipotetico dell'irrealtà al presente (εἰ + imperfetto ottat., ἄν + imperfetto). Si analizza κατηγόρους + participio (gli accusatori che vogliono). Contesto: l'oratoria giudiziaria ateniese.",
   [v("συνῄδη","fossi consapevole (imperf. irr. di σύνοιδα)"), v("βουλή","Consiglio (dei Cinquecento)"), v("ἐκ παντὸς τρόπου","in ogni modo"), v("κατηγορία","accusa"), v("πολλὴν χάριν ἔχειν","essere molto grato (idiom.)"), v("εἰ + imperf. / ἄν + imperf.","irrealtà al presente")],
   "Lo studente comprende il periodo ipotetico dell'irrealtà al presente. Analizza la costruzione κατήγοροι + participio. Legge l'esordio di una orazione di Lisia. Comprende le strategie retoriche dell'oratoria giudiziaria."),
  L("Τέλος Β1.3 καὶ τοῦ ὅλου πορείου. Ἀνεγνώκαμεν Αἰσχύλον, Σοφοκλέα, Εὐριπίδην, Ἀριστοφάνη, Πλάτωνα, Ἀριστοτέλην, Θουκυδίδην, Ξενοφῶντα, Λυσίαν. Αὕτη ἡ Ἑλλάς — ζῇ καὶ λαλεῖ πρὸς ἡμᾶς.",
   "Lezione conclusiva del B1.3 e dell'intero percorso di greco. Bilancio degli autori affrontati in tutto il percorso B1: tragici (Eschilo, Sofocle, Euripide), commedia (Aristofane), filosofia (Platone, Aristotele), storiografia (Tucidide, Senofonte), oratoria (Demostene, Lisia). La lingua greca come lingua viva.",
   [v("τοῦ ὅλου πορείου","dell'intero percorso (gen.)"), v("ζῇ","vive (ζάω, 3ª sing. contr.)"), v("λαλεῖ πρὸς ἡμᾶς","ci parla, parla a noi"), v("Αὕτη ἡ Ἑλλάς","questa è la Grecia (deittico)")],
   "Lo studente completa il B1.3 con una visione d'insieme della letteratura greca classica. Conosce gli autori principali e le loro caratteristiche stilistiche. Comprende il greco antico come lingua viva e culturalmente vitale. È in grado di leggere autonomamente testi autentici con supporto lessicale."),
]

IDS_GR_B11 = [
  "183e84e6-7836-4019-933f-e5382c175008",
  "5736511a-30e2-4ed0-b274-f860c29701f2",
  "0cb1d4e6-d8ad-40c0-8006-3514c3bc6313",
  "3e811b53-87f5-4ae4-a044-28ae1aba449c",
  "a9b3192c-be22-43da-b012-aeccf6ff81bb",
  "8eac5f8b-96b3-42d1-85ac-c4ff83e5d1c7",
  "ef54e40a-9d02-4072-9b09-7ad40b10f3ac",
  "1fa063ee-d445-4578-82bf-9491b32062bf",
  "776084d4-b46b-4184-8476-f36a4627182b",
  "7107c214-bf55-450a-a494-9d155c1adf8f",
  "b4d42ee4-0141-4074-893c-05b171d36908",
  "ab6b8501-35f6-4ccf-a344-b127f1534701",
  "57473aa5-5366-487d-892b-9c5fda80de2e",
  "824e613f-449d-426f-9306-ad942bca0bcd",
  "7c2b2284-522e-4f66-9093-3c5848391a63",
  "11680371-fc30-436e-b973-185ad1f784b2",
]
IDS_GR_B12 = [
  "19da92da-a249-4ce6-a3f7-3133b1ed2c9f",
  "2182617c-924d-4638-bd50-9e189d663bc2",
  "7de8962e-6700-4e68-a33b-7d6fe41b43d1",
  "9072cb18-ab4f-401f-9019-4d0dc9c3688b",
  "f19d714a-dc3f-4974-8091-e1916456c1d1",
  "2a7a4e8d-330f-433a-8cf6-c8ab1548c94a",
  "63724183-7882-4a3c-a4e2-67af3406b4cd",
  "fe9b033f-5796-420b-8a24-3d0b2d34b9e6",
  "6f541d45-671a-4b58-8b33-9616a0ce7821",
  "3325548a-4b4e-487b-8130-7e9ea7bcb32a",
  "596c5d82-34f0-457b-8035-539a768503c4",
  "d2fb8f07-7bec-446c-9b42-08014f33ab54",
]
IDS_GR_B13 = [
  "3aac7ca8-bb0b-4144-af8a-9f06f8afd641",
  "774d9f5f-709a-430d-b5ee-28ac59a5ee2e",
  "11a523fd-c835-4b38-b2fa-c5dd9f8d343e",
  "2a4691ab-75d8-432d-a0c2-af71f774e2d7",
  "e12251ab-61ef-406b-89e0-9a6def09f772",
  "cad7b782-71bb-4b82-954f-26653867950a",
  "77d474c0-477c-4dae-b3f4-6363e7cd5d2b",
  "e713a3c2-00d5-4b39-82da-085099298e57",
  "b44324fd-dcbc-4c1e-93b1-c6d64460aab4",
  "14d5d924-5185-4bdc-9e98-6ed0078ebfa1",
  "6775238c-fcdc-4cc5-8fa7-4d0a55f71d63",
  "7023ec17-691c-41de-a7f8-7a986513ee59",
]

def run():
    conn = psycopg2.connect(DB_URL)
    cur = conn.cursor()
    total = 0
    for ids, data, label in [
        (IDS_GR_B11, GR_B11, "gr-b11"),
        (IDS_GR_B12, GR_B12, "gr-b12"),
        (IDS_GR_B13, GR_B13, "gr-b13"),
    ]:
        assert len(ids) == len(data), f"{label}: {len(ids)} vs {len(data)}"
        for lid, lesson in zip(ids, data):
            cur.execute("""UPDATE "Lesson" SET "textFragment"=%s,"contentSummary"=%s,"keyVocabulary"=%s::jsonb,"learningObjectives"=%s WHERE id=%s""",
                (lesson["textFragment"], lesson["contentSummary"],
                 json.dumps(lesson["keyVocabulary"], ensure_ascii=False),
                 lesson["learningObjectives"], lid))
            total += 1
        print(f"  ✓ {label}: {len(data)} lezioni")
    conn.commit(); conn.close()
    print(f"Totale: {total}")

if __name__ == "__main__":
    run()
